// <auto-generated>
// This code was generated by the Calor compiler.
// Do not modify this file directly.
// </auto-generated>

#nullable enable

using System;
using Calor.Runtime;

namespace OutcomeRefuted
{
    public static class OutcomeRefutedModule
    {
        public static int Dec(int x)
        {
            // PROVEN: Precondition always satisfiable: x > 0
            int __result__ = default;

            #line 5 "/Users/juanrivera/sources/repos/juanmicrosoft/calor/tests/TestData/Verification/Outcomes/refuted-with-model.calr"
            __result__ = x - 1;
            #line default

            if (!(__result__ > 10)) throw new Calor.Runtime.ContractViolationException("Postcondition failed: __result__ > 10", "f1", Calor.Runtime.ContractKind.Ensures, startOffset: 73, length: 16, sourceFile: null, line: 4, column: 5, condition: "__result__ > 10");
            return __result__;
        }

    }
}
