// <auto-generated>
// This code was generated by the Calor compiler.
// Do not modify this file directly.
// </auto-generated>

#nullable enable

using System;

namespace FizzBuzz
{
    public static class FizzBuzzModule
    {
        public static void Main()
        {
            {
                var __calorForFrom = 1;
                var __calorForTo = 100;
                var __calorForStep = 1;
                if (__calorForStep == 0) throw new ArgumentOutOfRangeException(nameof(__calorForStep), "Calor for-loop step must not be zero");
                var __calorForAscending = __calorForStep > 0;
                var __calorForFirst = true;
                var i = __calorForFrom;
                while (true)
                {
                    if (!__calorForFirst)
                    {
                        try
                        {
                            checked
                            {
                                i += __calorForStep;
                            }
                        }
                        catch (OverflowException)
                        {
                            break;
                        }
                    }
                    else
                    {
                        __calorForFirst = false;
                    }
                    if (!(__calorForAscending ? i <= __calorForTo : i >= __calorForTo)) break;
                    if (i % 15 == 0)
                    {
                        Console.WriteLine("FizzBuzz");
                    }
                    else if (i % 3 == 0)
                    {
                        Console.WriteLine("Fizz");
                    }
                    else if (i % 5 == 0)
                    {
                        Console.WriteLine("Buzz");
                    }
                    else
                    {
                        Console.WriteLine(i);
                    }

                }
            }

        }

    }
}
