// <auto-generated>
// This code was generated by the Calor compiler.
// Do not modify this file directly.
// </auto-generated>

#nullable enable

using System;

namespace SkillSyntax
{
    public static class SkillSyntaxModule
    {
        public static void Main()
        {
            Console.WriteLine("=== Calor Skill Syntax Validation ===");
            Console.WriteLine("");
            TestArithmetic();
            TestComparison();
            TestControlFlow();
        }

        private static void TestArithmetic()
        {
            Console.WriteLine("Testing arithmetic operators...");
        }

        public static int Add(int a, int b)
        {
            return a + b;
        }

        public static int Subtract(int a, int b)
        {
            return a - b;
        }

        public static int Multiply(int a, int b)
        {
            return a * b;
        }

        private static void TestComparison()
        {
            Console.WriteLine("Testing comparison operators...");
        }

        public static bool IsPositive(int x)
        {
            return x > 0;
        }

        public static bool IsZero(int x)
        {
            return x == 0;
        }

        private static void TestControlFlow()
        {
            Console.WriteLine("Testing control flow...");
            {
                var __calorForFrom = 1;
                var __calorForTo = 5;
                var __calorForStep = 1;
                if (__calorForStep == 0) throw new ArgumentOutOfRangeException(nameof(__calorForStep), "Calor for-loop step must not be zero");
                var __calorForAscending = __calorForStep > 0;
                var __calorForFirst = true;
                var i = __calorForFrom;
                while (true)
                {
                    if (!__calorForFirst)
                    {
                        try
                        {
                            checked
                            {
                                i += __calorForStep;
                            }
                        }
                        catch (OverflowException)
                        {
                            break;
                        }
                    }
                    else
                    {
                        __calorForFirst = false;
                    }
                    if (!(__calorForAscending ? i <= __calorForTo : i >= __calorForTo)) break;
                    Console.WriteLine(i);
                }
            }

        }

    }
}
