// <auto-generated>
// This code was generated by the Calor compiler.
// Do not modify this file directly.
// </auto-generated>

#nullable enable

using System;
using System.Collections.Generic;
using System.Text;

namespace Transliterator
{
    public abstract class TransliteratorBase
    {
        public abstract string Name { get; }

    }

    public class CyrillicToLatin : TransliteratorBase
    {
        private string _mappings;
        public override string Name { get; }

        public CyrillicToLatin(string name)
        {
            this._mappings = name;
        }

        public string Transliterate(string input)
        {
            var dict = new Dictionary<char, string>();
            char[] buf = new char[256];
            var sb = new StringBuilder();
            ConsoleKeyInfo keyPressed = Console.ReadKey();
            {
                var __calorForFrom = 0;
                var __calorForTo = input.Length;
                var __calorForStep = 1;
                if (__calorForStep == 0) throw new ArgumentOutOfRangeException(nameof(__calorForStep), "Calor for-loop step must not be zero");
                var __calorForAscending = __calorForStep > 0;
                var __calorForFirst = true;
                var i = __calorForFrom;
                while (true)
                {
                    if (!__calorForFirst)
                    {
                        try
                        {
                            checked
                            {
                                i += __calorForStep;
                            }
                        }
                        catch (OverflowException)
                        {
                            break;
                        }
                    }
                    else
                    {
                        __calorForFirst = false;
                    }
                    if (!(__calorForAscending ? i <= __calorForTo : i >= __calorForTo)) break;
                    char ch = input[i];
                    if (ch == 'Y')
                    {
                        sb.Append("Y");
                    }
                    else
                    {
                        sb.Append(ch);
                    }

                }
            }

            Console.WriteLine("{0} {1}", new StringBuilder(), new StringBuilder());
            return sb.ToString();
        }

    }

}
