// <auto-generated>
// This code was generated by the Calor compiler.
// Do not modify this file directly.
// </auto-generated>

using System;
using Calor.Runtime;

namespace Generics
{
    public interface IRepository<T> where T : class
    {
        void Add(T item);
        IReadOnlyList<T> GetAll();
    }

    public class Pair<T, U>
    {
        public T First;
        public U Second;
        public Pair(T first, U second)
        {
            First = first;
            Second = second;
        }

    }

    public class Repository<T> where T : class
    {
        private List<T> _items;
        public Repository()
        {
            _items = new List<T>();
        }

        public void Add(T item)
        {
            _items.Add(item);
        }

        public IReadOnlyList<T> GetAll()
        {
            return _items;
        }

        public int Count()
        {
            return _items.Count;
        }

    }

    public static class GenericsModule
    {
        public static T Identity<T>(T value)
        {
            return value;
        }

        public static int GetCount<T>(List<T> items)
        {
            return items.Count;
        }

        public static void Main()
        {
            Console.WriteLine("Generics sample - compilation test");
            Console.WriteLine("Features demonstrated:");
            Console.WriteLine("  - Generic functions with type parameters");
            Console.WriteLine("  - Generic classes (Pair<T,U>, Repository<T>)");
            Console.WriteLine("  - Generic interfaces (IRepository<T>)");
            Console.WriteLine("  - WHERE constraints (T : class)");
            Console.WriteLine("  - Generic type references (List<T>, IReadOnlyList<T>)");
        }

    }
}
