using Calor.Compiler.Migration;
using Calor.Compiler.Mcp.Tools;
using Xunit;

namespace Calor.Compiler.Tests.PostConversion;

/// <summary>
/// Validates that the complex composed examples in calor-language-skills.md parse successfully.
/// Examples 2-4 are generated by the converter from real C# input.
/// </summary>
public class ComplexExampleValidationTests
{
    [Fact]
    public void Example_ClassWithFieldsCtorAndOperators_Parses()
    {
        // Hand-written example: §CL, §FLD, §CTOR, §OP, §MT
        var source = """
            §M{m001:PointModule}
            §CL{cl01:Point:pub}
              §FLD{i32:_x:pri}
              §FLD{i32:_y:pri}

              §CTOR{ct01:pub}
                §I{i32:x}
                §I{i32:y}
                §ASSIGN §THIS._x x
                §ASSIGN §THIS._y y
              §/CTOR{ct01}

              §MT{mt01:Equals:pub}
                §I{Point:other}
                §O{bool}
                §IF{if1} (== other null) → §R false
                §EL → §R true
                §/I{if1}
              §/MT{mt01}

              §OP{op01:==:pub}
                §I{Point:left}
                §I{Point:right}
                §O{bool}
                §IF{if1} (== left null) → §R (== right null)
                §EL → §R §C{left.Equals} §A right §/C
                §/I{if1}
              §/OP{op01}

              §OP{op02:!=:pub}
                §I{Point:left}
                §I{Point:right}
                §O{bool}
                §R (not (== left right))
              §/OP{op02}
            §/CL{cl01}
            §/M{m001}
            """;

        AssertParses(source, "ClassWithOperators");
    }

    [Fact]
    public void Example_AsyncTryCatch_ConverterGenerated_Parses()
    {
        // Generated by calor_convert from: async Task<string> FetchAsync(string url) with try/catch
        var source = """
            §M{m001:ConvertedModule}
              §U{System}
              §U{System.Threading.Tasks}

              §CL{c001:DataService:pub}
                §AMT{m002:FetchAsync:pub} (str:url) -> str
                  §TR{try003}
                    §B{_} §AWAIT §C{Task.Delay} §A 100 §/C
                    §R (+ "data from " url)
                  §CA{Exception:ex}
                    §R (+ "error: " ex.Message)
                  §/TR{try003}
                §/AMT{m002}

              §/CL{c001}

            §/M{m001}
            """;

        AssertParses(source, "AsyncTryCatch");
    }

    [Fact]
    public void Example_EnumWithSwitchMatch_ConverterGenerated_Parses()
    {
        // Generated by calor_convert from: enum Status + switch expression
        var source = """
            §M{m001:ConvertedModule}
              §EN{e001:Status}
                Pending
                Active
                Suspended
                Closed
              §/EN{e001}

              §CL{c002:StatusHelper:pub}
                §MT{m003:GetLabel:pub:stat} (Status:s) -> str
                  §W{match004:expr} s
                    §K Status.Pending → "Pending Review"
                    §K Status.Active → "Active"
                    §K Status.Suspended → "Temporarily Suspended"
                    §K Status.Closed → "Closed"
                    §K _ → "Unknown"
                  §/W{match004}
                §/MT{m003}

              §/CL{c002}

            §/M{m001}
            """;

        AssertParses(source, "EnumSwitch");
    }

    [Fact]
    public void Example_YieldIterator_ConverterGenerated_Parses()
    {
        // Generated by calor_convert from: IEnumerable<int> GetEvens(int max) with yield return
        var source = """
            §M{m001:ConvertedModule}
              §U{System.Collections.Generic}

              §CL{c001:NumberGen:pub}
                §MT{m002:GetEvens:pub} (i32:max) -> Seq<i32>
                  §L{for003:i:0:max:2}
                    §YIELD i
                  §/L{for003}
                §/MT{m002}

              §/CL{c001}

            §/M{m001}
            """;

        AssertParses(source, "YieldIterator");
    }

    [Fact]
    public void Example_HybridNativeWithCSharpInterop_Parses()
    {
        // Hand-written: native Calor class with one §CSHARP block
        var source = """
            §M{m001:HybridModule}
            §CL{cl01:DataProcessor:pub}
              §FLD{str:_connStr:pri}

              §CTOR{ct01:pub}
                §I{str:connStr}
                §ASSIGN §THIS._connStr connStr
              §/CTOR{ct01}

              §MT{mt01:GetCount:pub}
                §I{str:table}
                §O{i32}
                §B{query} (concat "SELECT COUNT(*) FROM " table)
                §R §C{Execute} §A _connStr §A query §/C
              §/MT{mt01}

              §CSHARP{
                public System.Data.DataTable RunQuery(string sql)
                {
                    using var conn = new System.Data.SqlClient.SqlConnection(_connStr);
                    conn.Open();
                    using var cmd = new System.Data.SqlClient.SqlCommand(sql, conn);
                    var adapter = new System.Data.SqlClient.SqlDataAdapter(cmd);
                    var table = new System.Data.DataTable();
                    adapter.Fill(table);
                    return table;
                }
              }§/CSHARP
            §/CL{cl01}
            §/M{m001}
            """;

        AssertParses(source, "HybridInterop");
    }

    private static void AssertParses(string source, string exampleName)
    {
        var result = CalorSourceHelper.Parse(source, $"{exampleName}.calr");
        if (!result.IsSuccess)
        {
            var errors = string.Join("\n  ", result.Errors);
            Assert.Fail($"Example '{exampleName}' failed to parse:\n  {errors}");
        }
    }
}
