using Calor.RoundTrip.Harness.TaskGen;
using Xunit;

namespace Calor.RoundTrip.Harness.Tests;

/// <summary>
/// Pins the D-S5.1 screen's verdict logic. The rule is gates §0.2's — 5 consecutive green runs
/// against the reference — and the failure modes that matter are the ones where a task could slip
/// through: too few runs, a red run, or a run that could not be executed at all.
/// </summary>
public class DeterminismScreenTests
{
    private static DeterminismScreen.RunRecord Run(bool green) => new()
    { TotalTests = 5, Passed = green ? 5 : 4, Failed = green ? 0 : 1, DurationMs = 800 };

    private static List<DeterminismScreen.RunRecord> Runs(params bool[] green) => green.Select(Run).ToList();

    /// <summary>Mutated-arm runs invert the sense: `true` means the defect MANIFESTED, i.e. the run was RED.</summary>
    private static List<DeterminismScreen.RunRecord> MutRuns(params bool[] manifested) =>
        manifested.Select(m => Run(!m)).ToList();

    private static DeterminismScreen.TaskScreen Screen(
        IReadOnlyList<bool> reference,
        IReadOnlyList<bool>? mutated = null,
        string? inconclusive = null,
        IReadOnlyList<bool>? calorReference = null,
        DeterminismScreen.ArmStatus arm = DeterminismScreen.ArmStatus.Ran) =>
        new()
        {
            TaskId = "t", ProjectName = "P", HeldOutFilter = "F",
            CSharpReferenceRuns = Runs([.. reference]),
            // Default the Calor arm to the same shape as the C# arm so existing cases keep testing
            // what they were written to test; the both-arms property gets its own case below.
            CalorReferenceRuns = Runs([.. calorReference ?? reference]),
            MutatedRuns = mutated == null ? MutRuns(true, true, true, true, true) : MutRuns([.. mutated]),
            MutatedArm = arm,
            Inconclusive = inconclusive,
        };

    private static readonly bool[] FiveGreen = [true, true, true, true, true];

    [Fact]
    public void Five_consecutive_green_reference_runs_pass()
    {
        var s = Screen(FiveGreen);
        Assert.True(s.Passes);
        Assert.Equal("PASS", s.Verdict);
    }

    [Fact]
    public void One_red_reference_run_fails_the_screen()
    {
        var s = Screen([true, true, false, true, true]);
        Assert.False(s.Passes);
        Assert.Contains("4/5", s.Verdict);
    }

    [Fact]
    public void Fewer_than_five_runs_fails_even_if_all_green()
    {
        // The rule is FIVE consecutive green, not "all the runs we managed were green" — a truncated
        // run must never be read as a pass.
        Assert.False(Screen([true, true, true, true]).Passes);
    }

    [Fact]
    public void Inconclusive_is_screened_out_conservatively_even_with_five_green()
    {
        // A build failure or a filter matching no tests cannot be evidence of determinism.
        var s = Screen(FiveGreen, inconclusive: "pristine reference did not build");
        Assert.False(s.Passes);
        Assert.StartsWith("INCONCLUSIVE", s.Verdict);
    }

    [Fact]
    public void An_intermittent_defect_still_passes_the_gate_but_is_reported()
    {
        // Gates §0.2 constrains the REFERENCE, not the defect's manifestation rate. A task whose
        // defect is intermittent is still screened in — but silently doing so would overstate the
        // epoch's discriminating power, so the verdict says it.
        var s = Screen(FiveGreen, mutated: [true, false, true, true, true]);
        Assert.True(s.Passes);
        Assert.False(s.DefectAlwaysManifests);
        Assert.Contains("defect intermittent", s.Verdict);
    }

    [Fact]
    public void Both_arms_must_be_green_a_red_calor_reference_fails()
    {
        // D-S5.1 applies the rule "on both arms". An earlier version screened only the pristine C#
        // corpus and reported it as passing "the" screen, leaving the Calor arm — where novel
        // nondeterminism is most likely — entirely unmeasured.
        var s = Screen(FiveGreen, calorReference: [true, true, false, true, true]);
        Assert.False(s.Passes);
        Assert.Contains("Calor 4/5", s.Verdict);
    }

    [Fact]
    public void A_missing_mutated_arm_is_reported_as_unavailable_not_intermittent()
    {
        // The bug: three conditions (arm absent, arm unbuildable, defect genuinely intermittent) all
        // produced "defect intermittent" — an affirmative false statement generated by an absent
        // directory, and the arms are gitignored working copies, so this was the COMMON case.
        var s = Screen(FiveGreen, mutated: [], arm: DeterminismScreen.ArmStatus.NotPresent);
        Assert.True(s.Passes);
        Assert.Equal("n/a — arm not available", s.MutatedNote);
        Assert.Equal("PASS", s.Verdict);
        Assert.DoesNotContain("intermittent", s.Verdict);
    }

    [Fact]
    public void A_run_with_no_tests_is_not_green()
    {
        // An empty filter runs the whole suite green; a filter matching nothing yields TotalTests 0.
        // Neither may count as evidence about the held-out set.
        var empty = new DeterminismScreen.RunRecord { TotalTests = 0, Passed = 0, Failed = 0, DurationMs = 10 };
        Assert.False(empty.Green);
    }

    [Fact]
    public void Result_counts_screened_rejected_and_intermittent()
    {
        var r = new DeterminismScreen.Result
        {
            CorpusPins = new Dictionary<string, string>(), HarnessCommit = "x",
            Tasks =
            [
                Screen(FiveGreen),
                Screen([true, false, true, true, true]),
                Screen(FiveGreen, mutated: [true, true, false, true, true]),
                Screen(FiveGreen, inconclusive: "no tests matched"),
                Screen(FiveGreen, mutated: [], arm: DeterminismScreen.ArmStatus.NotPresent),
            ]
        };

        Assert.Equal(3, r.Screened);
        Assert.Equal(2, r.Rejected);
        Assert.Equal(1, r.PassingWithIntermittentDefect);
        Assert.Equal(1, r.MutatedArmUnavailable);
    }

    [Fact]
    public void Report_states_the_rule_and_the_screened_count()
    {
        var md = DeterminismScreenReport.Render(new DeterminismScreen.Result
        {
            Tasks = [Screen(FiveGreen)],
            CorpusPins = new Dictionary<string, string> { ["Serilog"] = "abc123" },
            HarnessCommit = "def456",
        });
        Assert.Contains("5 consecutive green runs", md);
        Assert.Contains("**1 of 1 tasks pass.**", md);
        Assert.Contains("M-S3 counts only", md);
        Assert.Contains("on both arms", md);
        Assert.Contains("abc123", md);          // provenance is in the durable artifact
        Assert.Contains("41% at p=0.1", md);    // the instrument states its own power
    }
}
