// <auto-generated>
// This code was generated by the Calor compiler.
// Do not modify this file directly.
// </auto-generated>

#nullable enable

using System;

namespace CallbackAfter
{
    public class Counter
    {
        private Action<int> onChange;
        public void Bump(int n)
        {
            #line 6 "<source>.calr"
            onChange(n);
            #line default
        }

    }

}
