// <auto-generated>
// This code was generated by the Calor compiler.
// Do not modify this file directly.
// </auto-generated>

#nullable enable

using System;
using Calor.Runtime;
using System.Linq;

namespace QuantifierDemo
{
    public static class QuantifierDemoModule
    {
        public static bool AllNonNegative(int n)
        {
            if (!(Calor.Runtime.ContractQuantifier.Range(0, n).All(i => ((!(i >= 0 && i < n) || (i >= 0)))))) throw new Calor.Runtime.ContractViolationException("Precondition failed: Calor.Runtime.ContractQuantifier.Range(0, n).All(i => ((!(i >= 0 && i < n) || (i >= 0))))", "f001", Calor.Runtime.ContractKind.Requires, startOffset: 74, length: 57, sourceFile: null, line: 3, column: 5, condition: "Calor.Runtime.ContractQuantifier.Range(0, n).All(i => ((!(i >= 0 && i < n) || (i >= 0))))");
            return true;
        }

        public static bool ExistsTarget(int target)
        {
            if (!(Calor.Runtime.ContractQuantifier.Range(0, 10).Any(i => (i >= 0 && i < 10 && i == target)))) throw new Calor.Runtime.ContractViolationException("Precondition failed: Calor.Runtime.ContractQuantifier.Range(0, 10).Any(i => (i >= 0 && i < 10 && i == target))", "f002", Calor.Runtime.ContractKind.Requires, startOffset: 198, length: 63, sourceFile: null, line: 7, column: 5, condition: "Calor.Runtime.ContractQuantifier.Range(0, 10).Any(i => (i >= 0 && i < 10 && i == target))");
            bool __calorPostconditionResult0;
            __calorPostconditionResult0 = true;
            goto __calorPostconditionExit0;
            __calorPostconditionExit0:
            if (!(__calorPostconditionResult0 == true)) throw new Calor.Runtime.ContractViolationException("Postcondition failed: __calorPostconditionResult0 == true", "f002", Calor.Runtime.ContractKind.Ensures, startOffset: 266, length: 19, sourceFile: null, line: 8, column: 5, condition: "__calorPostconditionResult0 == true");
            return __calorPostconditionResult0;
        }

        public static bool ImplicationTest(int x)
        {
            if (!((!(x > 0) || (x >= 0)))) throw new Calor.Runtime.ContractViolationException("Precondition failed: (!(x > 0) || (x >= 0))", "f003", Calor.Runtime.ContractKind.Requires, startOffset: 350, length: 24, sourceFile: null, line: 12, column: 5, condition: "(!(x > 0) || (x >= 0))");
            return true;
        }

        public static bool MatrixSymmetry(int n, int m)
        {
            if (!(Calor.Runtime.ContractQuantifier.Range(0, n).All(i => (Calor.Runtime.ContractQuantifier.Range(0, m).All(j => ((!(i >= 0 && i < n && j >= 0 && j < m) || (i >= 0)))))))) throw new Calor.Runtime.ContractViolationException("Precondition failed: Calor.Runtime.ContractQuantifier.Range(0, n).All(i => (Calor.Runtime.ContractQuantifier.Range(0, m).All(j => ((!(i >= 0 && i < n && j >= 0 && j < m) || (i >= 0))))))", "f004", Calor.Runtime.ContractKind.Requires, startOffset: 445, length: 92, sourceFile: null, line: 16, column: 5, condition: "Calor.Runtime.ContractQuantifier.Range(0, n).All(i => (Calor.Runtime.ContractQuantifier.Range(0, m).All(j => ((!(i >= 0 && i < n && j >= 0 && j < m) || (i >= 0))))))");
            return true;
        }

    }
}
