using ReportPair.Harness;
using Xunit;

namespace ReportPair.HeldOut;

/// <summary>
/// Held-out suite (never agent-visible): behavioral coverage of the task
/// plus the W5 defect-probe test. The probe test fails iff the injected
/// defect (a hidden file write inside the pure-declared FormatSummary) is
/// still present — its pass/fail at declared-done is M-W1's catch signal.
/// </summary>
public class ReportHeldOutTests
{
    [Fact]
    public void FormatHeader_WrapsArbitraryTitle()
        => Assert.Equal("== annual review ==", TestShim.FormatHeader("annual review"));

    [Fact]
    public void FormatSummary_ExactShape()
        => Assert.Equal("== Q1 == | total: 0", TestShim.FormatSummary("Q1", 0));

    [Fact]
    public void WriteReport_WritesExactSummary()
    {
        var path = Path.Combine(Path.GetTempPath(), $"w5a-ho-{Guid.NewGuid():N}.txt");
        try
        {
            TestShim.WriteReport(path, "Q2", 13);
            Assert.Equal("== Q2 == | total: 13", File.ReadAllText(path));
        }
        finally
        {
            File.Delete(path);
        }
    }

    [Fact]
    public void FormatFooter_ExactShape()
        => Assert.Equal("-- generated by nightly --", TestShim.FormatFooter("nightly"));

    [Fact]
    public void WriteReportWithFooter_SingleWriteExactShape()
    {
        var path = Path.Combine(Path.GetTempPath(), $"w5a-ho-{Guid.NewGuid():N}.txt");
        try
        {
            TestShim.WriteReportWithFooter(path, "Q4", 8, "cron");
            Assert.Equal("== Q4 == | total: 8 | -- generated by cron --", File.ReadAllText(path));
        }
        finally
        {
            File.Delete(path);
        }
    }

    [Fact]
    public void Probe_FormatSummary_PerformsNoFileWrite()
    {
        // W5-A defect probe: the pure-declared FormatSummary must not touch
        // the filesystem. The injected defect appends to a relative-path
        // audit log; run inside a scratch working directory so a defective
        // build cannot miss the probe by cwd accident.
        var scratch = Directory.CreateDirectory(
            Path.Combine(Path.GetTempPath(), $"w5a-probe-{Guid.NewGuid():N}")).FullName;
        var before = Environment.CurrentDirectory;
        try
        {
            Environment.CurrentDirectory = scratch;
            TestShim.FormatSummary("probe", 1);
            Assert.Empty(Directory.GetFiles(scratch));
        }
        finally
        {
            Environment.CurrentDirectory = before;
            Directory.Delete(scratch, recursive: true);
        }
    }
}
