// <auto-generated>
// This code was generated by the Calor compiler.
// Do not modify this file directly.
// </auto-generated>

#nullable enable

using System;
using Calor.Runtime;

namespace ContractZ3Test
{
    public interface IService
    {
        /// <summary>
        /// Interface method with contracts.
        /// </summary>
        /// <remarks>Requires: value >= 0</remarks>
        int Process(int value);
    }

    public class ValidService : IService
    {
        public int Process(int value)
        {
            if (!(value >= -10)) throw new Calor.Runtime.ContractViolationException("Precondition failed: value >= -10", "mt001", Calor.Runtime.ContractKind.Requires, startOffset: 214, length: 17, sourceFile: null, line: 10, column: 7, condition: "value >= -10");
            int __calorPostconditionResult0;
            __calorPostconditionResult0 = value + 1;
            goto __calorPostconditionExit0;
            __calorPostconditionExit0:
            if (!(__calorPostconditionResult0 >= 1)) throw new Calor.Runtime.ContractViolationException("Postcondition failed: __calorPostconditionResult0 >= 1", "mt001", Calor.Runtime.ContractKind.Ensures, startOffset: 238, length: 16, sourceFile: null, line: 11, column: 7, condition: "__calorPostconditionResult0 >= 1");
            return __calorPostconditionResult0;
        }

    }

    public class AnotherValidService : IService
    {
        public int Process(int value)
        {
            if (!(value >= 0)) throw new Calor.Runtime.ContractViolationException("Precondition failed: value >= 0", "mt002", Calor.Runtime.ContractKind.Requires, startOffset: 387, length: 15, sourceFile: null, line: 19, column: 7, condition: "value >= 0");
            int __calorPostconditionResult1;
            __calorPostconditionResult1 = value + 10;
            goto __calorPostconditionExit1;
            __calorPostconditionExit1:
            if (!(__calorPostconditionResult1 >= 10)) throw new Calor.Runtime.ContractViolationException("Postcondition failed: __calorPostconditionResult1 >= 10", "mt002", Calor.Runtime.ContractKind.Ensures, startOffset: 409, length: 17, sourceFile: null, line: 20, column: 7, condition: "__calorPostconditionResult1 >= 10");
            return __calorPostconditionResult1;
        }

    }

}
