// <auto-generated>
// This code was generated by the Calor compiler.
// Do not modify this file directly.
// </auto-generated>

#nullable enable

using System;
using Calor.Runtime;

namespace ContractZ3Test
{
    public interface IService
    {
        int Process(int value);
    }

    public class ValidService : IService
    {
        public int Process(int value)
        {
            if (!(value >= -10)) throw new Calor.Runtime.ContractViolationException("Precondition failed: value >= -10", "unknown", Calor.Runtime.ContractKind.Requires, startOffset: 192, length: 17, sourceFile: null, line: 9, column: 7, condition: "value >= -10");
            int __result__ = default;

            __result__ = value + 1;

            if (!(__result__ >= 1)) throw new Calor.Runtime.ContractViolationException("Postcondition failed: __result__ >= 1", "unknown", Calor.Runtime.ContractKind.Ensures, startOffset: 216, length: 16, sourceFile: null, line: 10, column: 7, condition: "__result__ >= 1");
            return __result__;
        }

    }

    public class AnotherValidService : IService
    {
        public int Process(int value)
        {
            if (!(value >= 0)) throw new Calor.Runtime.ContractViolationException("Precondition failed: value >= 0", "unknown", Calor.Runtime.ContractKind.Requires, startOffset: 365, length: 15, sourceFile: null, line: 18, column: 7, condition: "value >= 0");
            int __result__ = default;

            __result__ = value + 10;

            if (!(__result__ >= 10)) throw new Calor.Runtime.ContractViolationException("Postcondition failed: __result__ >= 10", "unknown", Calor.Runtime.ContractKind.Ensures, startOffset: 387, length: 17, sourceFile: null, line: 19, column: 7, condition: "__result__ >= 10");
            return __result__;
        }

    }

}
