using System.Text.RegularExpressions;

namespace Calor.Compiler.Tests;

/// <summary>
/// The one path rule the committed-corpus census walkers use to skip the
/// <b>PP-W-rows</b> measurement fixtures (roadmap v0.16 §4.1, entry-gate spike S3 (c)).
///
/// <para><b>What it covers.</b> Two shapes, both keyed on a <c>W-&lt;three digits&gt;-</c>
/// pair id:</para>
/// <list type="bullet">
///   <item><description><c>bench/phase0-agent-native/pairs/W-001-…/</c> — the pair
///   fixtures. Twelve of the files are byte-identical copies of the emitter spike's
///   <c>before/*.calr</c> and <c>after/*.calr</c> (frozen by blob SHA at <c>7d621c0d</c>)
///   used as per-arm starters; the rest are seeded shortcut / clean / recorded-confound
///   mutants of them. Rows are their subject matter, not an accident.</description></item>
///   <item><description><c>bench/phase0-agent-native/epochs/&lt;epoch&gt;/W-001-…/</c> —
///   the per-run archives a PP-W-rows epoch writes. Every arm-B run archives
///   <c>final-src/*.calr</c> carrying the starter's inline parameter rows verbatim, so
///   without this rule the first epoch would red the shape pin and drift the tracked-file
///   count — a ledger regenerated by the workstream that runs the probe, which §4.1
///   adjudicates as an own-goal MISS.</description></item>
/// </list>
///
/// <para><b>Starters are inside the rule, and that is the disposition v0.16 W1 asked for.</b>
/// W1 (#1119) landed the narrow form — <c>pairs/W-\d{3}-*/seeded/</c> only — and left a note
/// saying the per-arm starters "must be dispositioned" when the pairs land, because 9 of the
/// <c>starter-b</c> files write inline parameter rows and same-line <c>§FLD … §E{…}</c>, exactly
/// the forms <c>EffectRowCorpusShapeTests</c> asserts no committed <c>.calr</c> writes. Of the
/// three options it listed — exclude the starters, retire the §3.2 claim, or rewrite the
/// fixtures — only the first is available: the starters are frozen by blob SHA at
/// <c>7d621c0d</c> (§4.1 route (a) reads their multisets, and
/// <c>test_ppw_pairs.py</c> asserts the bytes), so they cannot be rewritten, and the §3.2 claim
/// is about programs written before the line rule, which these are not. So the whole pair family
/// is excluded and the §3.2 claim keeps its meaning over the corpus it is about. It also keeps
/// the corpus counts where they are: including the 12 starters would move the census 927 → 939
/// and force a formatter-baseline regeneration from this workstream.</para>
///
/// <para><b>Why it is the same rule as <c>docs/design/spikes/</c>.</b> These are
/// deliberately frozen measurement inputs, not source any corpus baseline speaks for.
/// The narrower <c>epochs/**/final-src/</c> would not do: 210 committed archive
/// <c>.calr</c> from four earlier epochs are inside today's counts (the 926 pin is
/// 886 + <c>e1-rows-parity-001</c>'s 40), so excluding all of them would regenerate
/// every ledger here. Keyed on the pair id, this rule matches <b>nothing</b> in the
/// tree today beyond the pair directories themselves, and the counts are unchanged.</para>
///
/// <para>Anchored and digit-precise on purpose: a prefix like <c>"…/pairs/W-00"</c>
/// would silently stop covering a later <c>W-010-…</c> pair.</para>
/// </summary>
internal static class PpwFixture
{
    private static readonly Regex Pattern = new(
        @"^bench/phase0-agent-native/(pairs|epochs/[^/]+)/W-\d{3}-",
        RegexOptions.Compiled | RegexOptions.CultureInvariant);

    /// <summary>True when a repo-relative path is a PP-W-rows fixture or epoch archive.</summary>
    internal static bool IsMatch(string repoRelativePath) => Pattern.IsMatch(repoRelativePath);
}
