using System.Text.RegularExpressions;

namespace Calor.Compiler.Tests;

/// <summary>
/// The one path rule the committed-corpus census walkers use to skip the
/// <b>PP-W-rows</b> measurement fixtures (roadmap v0.16 §4.1, entry-gate spike S3 (c)).
///
/// <para><b>What it covers.</b> Two shapes, both keyed on a <c>W-&lt;three digits&gt;-</c>
/// pair id:</para>
/// <list type="bullet">
///   <item><description><c>bench/phase0-agent-native/pairs/W-001-…/</c> — the pair
///   fixtures. Twelve of the files are byte-identical copies of the emitter spike's
///   <c>before/*.calr</c> and <c>after/*.calr</c> (frozen by blob SHA at <c>7d621c0d</c>)
///   used as per-arm starters; the rest are seeded shortcut / clean / recorded-confound
///   mutants of them. Rows are their subject matter, not an accident.</description></item>
///   <item><description><c>bench/phase0-agent-native/epochs/&lt;epoch&gt;/W-001-…/</c> —
///   the per-run archives a PP-W-rows epoch writes. Every arm-B run archives
///   <c>final-src/*.calr</c> carrying the starter's inline parameter rows verbatim, so
///   without this rule the first epoch would red the shape pin and drift the tracked-file
///   count — a ledger regenerated by the workstream that runs the probe, which §4.1
///   adjudicates as an own-goal MISS.</description></item>
/// </list>
///
/// <para><b>Why it is the same rule as <c>docs/design/spikes/</c>.</b> These are
/// deliberately frozen measurement inputs, not source any corpus baseline speaks for.
/// The narrower <c>epochs/**/final-src/</c> would not do: 210 committed archive
/// <c>.calr</c> from four earlier epochs are inside today's counts (the 926 pin is
/// 886 + <c>e1-rows-parity-001</c>'s 40), so excluding all of them would regenerate
/// every ledger here. Keyed on the pair id, this rule matches <b>nothing</b> in the
/// tree today beyond the pair directories themselves, and the counts are unchanged.</para>
///
/// <para>Anchored and digit-precise on purpose: a prefix like <c>"…/pairs/W-00"</c>
/// would silently stop covering a later <c>W-010-…</c> pair.</para>
/// </summary>
internal static class PpwFixture
{
    private static readonly Regex Pattern = new(
        @"^bench/phase0-agent-native/(pairs|epochs/[^/]+)/W-\d{3}-",
        RegexOptions.Compiled | RegexOptions.CultureInvariant);

    /// <summary>True when a repo-relative path is a PP-W-rows fixture or epoch archive.</summary>
    internal static bool IsMatch(string repoRelativePath) => Pattern.IsMatch(repoRelativePath);
}
