#!/usr/bin/env python3
"""Generate visitor interfaces and centralized dispatch from eng/ast-schema.json."""

from __future__ import annotations

import argparse
import json
import pathlib
import re
import sys


ROOT = pathlib.Path(__file__).resolve().parents[1]
SCHEMA_PATH = ROOT / "eng" / "ast-schema.json"
AST_NODE_PATH = ROOT / "src" / "Calor.Compiler" / "Ast" / "AstNode.cs"
AST_DIRECTORY = AST_NODE_PATH.parent
START_MARKER = "// <generated-ast-infrastructure>"
END_MARKER = "// </generated-ast-infrastructure>"
OVERRIDE_PATTERN = re.compile(
    r"^\s*public override (?:void|T) Accept(?:<T>)?"
    r"\([^)]*\) => visitor\.Visit\(this\);\s*$",
    re.MULTILINE,
)


def load_nodes() -> list[dict[str, str]]:
    schema = json.loads(SCHEMA_PATH.read_text(encoding="utf-8"))
    nodes = schema["nodes"]
    names = [entry["name"] for entry in nodes]
    if len(names) != len(set(names)):
        raise ValueError("eng/ast-schema.json contains duplicate AST node names")
    return nodes


def render(entries: list[dict[str, str]]) -> str:
    nodes = [entry["name"] for entry in entries]
    void_methods = "\n".join(f"    void Visit({node} node);" for node in nodes)
    value_methods = "\n".join(f"    T Visit({node} node);" for node in nodes)
    void_cases = "\n".join(
        f"            case {node} typed: visitor.Visit(typed); return;" for node in nodes
    )
    value_cases = "\n".join(
        f"            {node} typed => visitor.Visit(typed)," for node in nodes
    )
    descriptors = "\n".join(
        f'        Create<{entry["name"]}>("{entry["source"]}"),'
        for entry in entries
    )
    return f"""{START_MARKER}
// Generated by scripts/generate_ast_infrastructure.py. Do not edit this region.
public interface IAstVisitor
{{
{void_methods}
}}

public interface IAstVisitor<T>
{{
{value_methods}
}}

public sealed record AstNodeSchemaEntry(
    Type NodeType,
    string SourceFile,
    IReadOnlyList<string> ChildProperties);

public static class AstSchemaMetadata
{{
    public static IReadOnlyList<AstNodeSchemaEntry> Nodes {{ get; }} =
    [
{descriptors}
    ];

    public static IReadOnlyList<Type> NodeTypes {{ get; }} =
        Nodes.Select(node => node.NodeType).ToArray();

    private static AstNodeSchemaEntry Create<TNode>(string sourceFile)
        where TNode : AstNode
        => new(
            typeof(TNode),
            sourceFile,
            typeof(TNode)
                .GetProperties(System.Reflection.BindingFlags.Public |
                    System.Reflection.BindingFlags.Instance)
                .Where(property => property.GetIndexParameters().Length == 0)
                .Where(property => CanContainAstNode(property.PropertyType))
                .Select(property => property.Name)
                .OrderBy(name => name, StringComparer.Ordinal)
                .ToArray());

    private static bool CanContainAstNode(Type type)
    {{
        if (typeof(AstNode).IsAssignableFrom(type))
            return true;
        if (type == typeof(string))
            return false;
        return type.GetInterfaces()
            .Prepend(type)
            .Where(candidate => candidate.IsGenericType)
            .Where(candidate =>
                candidate.GetGenericTypeDefinition() == typeof(IEnumerable<>))
            .Select(candidate => candidate.GetGenericArguments()[0])
            .Any(typeof(AstNode).IsAssignableFrom);
    }}
}}

internal static class AstVisitorDispatch
{{
    public static void Visit(IAstVisitor visitor, AstNode node)
    {{
        ArgumentNullException.ThrowIfNull(visitor);
        ArgumentNullException.ThrowIfNull(node);
        switch (node)
        {{
{void_cases}
            default:
                throw new InvalidOperationException(
                    $"AST node '{{node.GetType().FullName}}' is absent from eng/ast-schema.json.");
        }}
    }}

    public static T Visit<T>(IAstVisitor<T> visitor, AstNode node)
    {{
        ArgumentNullException.ThrowIfNull(visitor);
        ArgumentNullException.ThrowIfNull(node);
        return node switch
        {{
{value_cases}
            _ => throw new InvalidOperationException(
                $"AST node '{{node.GetType().FullName}}' is absent from eng/ast-schema.json.")
        }};
    }}
}}
{END_MARKER}"""


def replace_generated_region(text: str, generated: str) -> str:
    start = text.index(START_MARKER)
    end = text.index(END_MARKER, start) + len(END_MARKER)
    return text[:start] + generated + text[end:]


def normalize_ast_node(text: str) -> str:
    text = text.replace(
        "    public abstract void Accept(IAstVisitor visitor);\n"
        "    public abstract T Accept<T>(IAstVisitor<T> visitor);",
        "    public virtual void Accept(IAstVisitor visitor) => AstVisitorDispatch.Visit(visitor, this);\n"
        "    public virtual T Accept<T>(IAstVisitor<T> visitor) => AstVisitorDispatch.Visit(visitor, this);",
    )
    return OVERRIDE_PATTERN.sub("", text)


def expected_files(nodes: list[dict[str, str]]) -> dict[pathlib.Path, str]:
    expected: dict[pathlib.Path, str] = {}
    ast_node = normalize_ast_node(AST_NODE_PATH.read_text(encoding="utf-8"))
    expected[AST_NODE_PATH] = replace_generated_region(ast_node, render(nodes))
    for path in AST_DIRECTORY.glob("*.cs"):
        if path == AST_NODE_PATH:
            continue
        expected[path] = normalize_ast_node(path.read_text(encoding="utf-8"))
    return expected


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument(
        "--check",
        action="store_true",
        help="fail when generated infrastructure is stale",
    )
    args = parser.parse_args()
    expected = expected_files(load_nodes())
    stale = [
        path.relative_to(ROOT)
        for path, content in expected.items()
        if path.read_text(encoding="utf-8") != content
    ]
    if args.check:
        if stale:
            print("Generated AST infrastructure is stale:", file=sys.stderr)
            for path in stale:
                print(f"  {path}", file=sys.stderr)
            print(
                "Run: python3 scripts/generate_ast_infrastructure.py",
                file=sys.stderr,
            )
            return 1
        return 0
    for path, content in expected.items():
        path.write_text(content, encoding="utf-8")
    print(f"Generated AST infrastructure for {len(load_nodes())} nodes.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
