// <auto-generated>
// This code was generated by the OPAL compiler.
// Do not modify this file directly.
// </auto-generated>

using System;
using Opal.Runtime;

namespace Contracts
{
    public static class ContractsModule
    {
        public static void Main()
        {
            Console.WriteLine("Testing contracts...");
        }

        public static int Square(int x)
        {
            if (!((x >= 0))) throw new ArgumentException("Precondition failed: (x >= 0)");
            int __result__ = default;

            __result__ = (x * x);

            if (!((__result__ >= 0))) throw new InvalidOperationException("Postcondition failed: (__result__ >= 0)");
            return __result__;
        }

        public static int Divide(int a, int b)
        {
            if (!((b != 0))) throw new ArgumentException("divisor must not be zero");
            return (a / b);
        }

    }
}
