using Calor.Compiler.Parsing;

namespace Calor.Compiler.Ast;

/// <summary>
/// Base class for all AST nodes.
/// </summary>
public abstract class AstNode
{
    public TextSpan Span { get; }

    /// <summary>
    /// Fully-qualified C# namespace associated with this declaration.
    /// <c>null</c> means legacy module-level namespace inheritance and an empty
    /// string means the explicit global namespace.
    /// </summary>
    public string? NamespaceIdentity { get; set; }

    /// <summary>
    /// Identity of the lexical namespace declaration that contains this node.
    /// Separate declarations of the same namespace intentionally have distinct
    /// scope IDs because their using aliases do not share a lexical scope.
    /// </summary>
    public string? NamespaceScopeId { get; set; }

    /// <summary>
    /// Fully-qualified symbol identity used by recovery, source mapping, and
    /// partial-type merging.
    /// </summary>
    public string? FullyQualifiedSymbolIdentity { get; set; }

    /// <summary>
    /// Optional XML doc comment extracted during C# → Calor conversion.
    /// Emitted as line comments above the construct.
    /// </summary>
    public string? DocComment { get; set; }

    protected AstNode(TextSpan span)
    {
        Span = span;
    }

    internal T CopyMetadataTo<T>(T target) where T : AstNode
    {
        ArgumentNullException.ThrowIfNull(target);
        target.NamespaceIdentity = NamespaceIdentity;
        target.NamespaceScopeId = NamespaceScopeId;
        target.FullyQualifiedSymbolIdentity = FullyQualifiedSymbolIdentity;
        target.DocComment = DocComment;
        return target;
    }

    public virtual void Accept(IAstVisitor visitor) => AstVisitorDispatch.Visit(visitor, this);
    public virtual T Accept<T>(IAstVisitor<T> visitor) => AstVisitorDispatch.Visit(visitor, this);
}

// <generated-ast-infrastructure>
// Generated by scripts/generate_ast_infrastructure.py. Do not edit this region.
public interface IAstVisitor
{
    void Visit(ModuleNode node);
    void Visit(FunctionNode node);
    void Visit(OutputNode node);
    void Visit(EffectsNode node);
    void Visit(ParameterNode node);
    void Visit(CallStatementNode node);
    void Visit(ReturnStatementNode node);
    void Visit(IntLiteralNode node);
    void Visit(StringLiteralNode node);
    void Visit(BoolLiteralNode node);
    void Visit(ConditionalExpressionNode node);
    void Visit(FloatLiteralNode node);
    void Visit(DecimalLiteralNode node);
    void Visit(ReferenceNode node);
    void Visit(ForStatementNode node);
    void Visit(WhileStatementNode node);
    void Visit(DoWhileStatementNode node);
    void Visit(IfStatementNode node);
    void Visit(ElseIfClauseNode node);
    void Visit(BindStatementNode node);
    void Visit(BinaryOperationNode node);
    void Visit(UnaryOperationNode node);
    void Visit(ContinueStatementNode node);
    void Visit(BreakStatementNode node);
    void Visit(GotoStatementNode node);
    void Visit(LabelStatementNode node);
    void Visit(PrintStatementNode node);
    void Visit(RecordDefinitionNode node);
    void Visit(FieldDefinitionNode node);
    void Visit(UnionTypeDefinitionNode node);
    void Visit(VariantDefinitionNode node);
    void Visit(TypeReferenceNode node);
    void Visit(EnumDefinitionNode node);
    void Visit(EnumMemberNode node);
    void Visit(EnumExtensionNode node);
    void Visit(RecordCreationNode node);
    void Visit(FieldAssignmentNode node);
    void Visit(FieldAccessNode node);
    void Visit(SomeExpressionNode node);
    void Visit(NoneExpressionNode node);
    void Visit(OkExpressionNode node);
    void Visit(ErrExpressionNode node);
    void Visit(MatchExpressionNode node);
    void Visit(MatchStatementNode node);
    void Visit(MatchCaseNode node);
    void Visit(WildcardPatternNode node);
    void Visit(VariablePatternNode node);
    void Visit(LiteralPatternNode node);
    void Visit(SomePatternNode node);
    void Visit(NonePatternNode node);
    void Visit(OkPatternNode node);
    void Visit(ErrPatternNode node);
    void Visit(RequiresNode node);
    void Visit(EnsuresNode node);
    void Visit(InvariantNode node);
    void Visit(UsingDirectiveNode node);
    void Visit(ArrayCreationNode node);
    void Visit(ArrayAccessNode node);
    void Visit(ArrayLengthNode node);
    void Visit(ForeachStatementNode node);
    void Visit(ListCreationNode node);
    void Visit(DictionaryCreationNode node);
    void Visit(KeyValuePairNode node);
    void Visit(SetCreationNode node);
    void Visit(CollectionPushNode node);
    void Visit(DictionaryPutNode node);
    void Visit(CollectionRemoveNode node);
    void Visit(CollectionSetIndexNode node);
    void Visit(CollectionClearNode node);
    void Visit(CollectionInsertNode node);
    void Visit(CollectionContainsNode node);
    void Visit(DictionaryForeachNode node);
    void Visit(CollectionCountNode node);
    void Visit(TypeParameterNode node);
    void Visit(TypeConstraintNode node);
    void Visit(GenericTypeNode node);
    void Visit(InterfaceDefinitionNode node);
    void Visit(MethodSignatureNode node);
    void Visit(ClassDefinitionNode node);
    void Visit(ClassFieldNode node);
    void Visit(MethodNode node);
    void Visit(NewExpressionNode node);
    void Visit(AnonymousObjectCreationNode node);
    void Visit(CallExpressionNode node);
    void Visit(ThisExpressionNode node);
    void Visit(BaseExpressionNode node);
    void Visit(TupleLiteralNode node);
    void Visit(PropertyNode node);
    void Visit(IndexerNode node);
    void Visit(PropertyAccessorNode node);
    void Visit(ConstructorNode node);
    void Visit(OperatorOverloadNode node);
    void Visit(ConstructorInitializerNode node);
    void Visit(AssignmentStatementNode node);
    void Visit(CompoundAssignmentStatementNode node);
    void Visit(UsingStatementNode node);
    void Visit(TryStatementNode node);
    void Visit(CatchClauseNode node);
    void Visit(ThrowStatementNode node);
    void Visit(ThrowExpressionNode node);
    void Visit(RethrowStatementNode node);
    void Visit(LambdaParameterNode node);
    void Visit(LambdaExpressionNode node);
    void Visit(DelegateDefinitionNode node);
    void Visit(EventDefinitionNode node);
    void Visit(EventSubscribeNode node);
    void Visit(EventUnsubscribeNode node);
    void Visit(AwaitExpressionNode node);
    void Visit(InterpolatedStringNode node);
    void Visit(InterpolatedStringTextNode node);
    void Visit(InterpolatedStringExpressionNode node);
    void Visit(NullCoalesceNode node);
    void Visit(NullConditionalNode node);
    void Visit(RangeExpressionNode node);
    void Visit(IndexFromEndNode node);
    void Visit(WithExpressionNode node);
    void Visit(WithPropertyAssignmentNode node);
    void Visit(PositionalPatternNode node);
    void Visit(PropertyPatternNode node);
    void Visit(PropertyMatchNode node);
    void Visit(RelationalPatternNode node);
    void Visit(ListPatternNode node);
    void Visit(VarPatternNode node);
    void Visit(ConstantPatternNode node);
    void Visit(NegatedPatternNode node);
    void Visit(OrPatternNode node);
    void Visit(AndPatternNode node);
    void Visit(TypePatternNode node);
    void Visit(ExampleNode node);
    void Visit(IssueNode node);
    void Visit(DependencyNode node);
    void Visit(UsesNode node);
    void Visit(UsedByNode node);
    void Visit(AssumeNode node);
    void Visit(ComplexityNode node);
    void Visit(SinceNode node);
    void Visit(DeprecatedNode node);
    void Visit(BreakingChangeNode node);
    void Visit(DecisionNode node);
    void Visit(RejectedOptionNode node);
    void Visit(ContextNode node);
    void Visit(FileRefNode node);
    void Visit(PropertyTestNode node);
    void Visit(LockNode node);
    void Visit(AuthorNode node);
    void Visit(TaskRefNode node);
    void Visit(CalorAttributeNode node);
    void Visit(QuantifierVariableNode node);
    void Visit(ForallExpressionNode node);
    void Visit(ExistsExpressionNode node);
    void Visit(ImplicationExpressionNode node);
    void Visit(StringOperationNode node);
    void Visit(CharOperationNode node);
    void Visit(StringBuilderOperationNode node);
    void Visit(TypeOperationNode node);
    void Visit(IsPatternNode node);
    void Visit(ExpressionStatementNode node);
    void Visit(FallbackExpressionNode node);
    void Visit(FallbackCommentNode node);
    void Visit(TypeOfExpressionNode node);
    void Visit(NameOfExpressionNode node);
    void Visit(ExpressionCallNode node);
    void Visit(YieldReturnStatementNode node);
    void Visit(YieldBreakStatementNode node);
    void Visit(RawCSharpNode node);
    void Visit(CompilerDirectiveNode node);
    void Visit(CSharpInteropBlockNode node);
    void Visit(StackAllocNode node);
    void Visit(UnsafeBlockNode node);
    void Visit(FixedStatementNode node);
    void Visit(AddressOfNode node);
    void Visit(PointerDereferenceNode node);
    void Visit(SizeOfNode node);
    void Visit(MultiDimArrayCreationNode node);
    void Visit(MultiDimArrayAccessNode node);
    void Visit(RawCSharpExpressionNode node);
    void Visit(PreprocessorDirectiveNode node);
    void Visit(MemberPreprocessorBlockNode node);
    void Visit(TypePreprocessorBlockNode node);
    void Visit(RefinementTypeNode node);
    void Visit(SelfRefNode node);
    void Visit(ProofObligationNode node);
    void Visit(IndexedTypeNode node);
    void Visit(SyncBlockNode node);
}

public interface IAstVisitor<T>
{
    T Visit(ModuleNode node);
    T Visit(FunctionNode node);
    T Visit(OutputNode node);
    T Visit(EffectsNode node);
    T Visit(ParameterNode node);
    T Visit(CallStatementNode node);
    T Visit(ReturnStatementNode node);
    T Visit(IntLiteralNode node);
    T Visit(StringLiteralNode node);
    T Visit(BoolLiteralNode node);
    T Visit(ConditionalExpressionNode node);
    T Visit(FloatLiteralNode node);
    T Visit(DecimalLiteralNode node);
    T Visit(ReferenceNode node);
    T Visit(ForStatementNode node);
    T Visit(WhileStatementNode node);
    T Visit(DoWhileStatementNode node);
    T Visit(IfStatementNode node);
    T Visit(ElseIfClauseNode node);
    T Visit(BindStatementNode node);
    T Visit(BinaryOperationNode node);
    T Visit(UnaryOperationNode node);
    T Visit(ContinueStatementNode node);
    T Visit(BreakStatementNode node);
    T Visit(GotoStatementNode node);
    T Visit(LabelStatementNode node);
    T Visit(PrintStatementNode node);
    T Visit(RecordDefinitionNode node);
    T Visit(FieldDefinitionNode node);
    T Visit(UnionTypeDefinitionNode node);
    T Visit(VariantDefinitionNode node);
    T Visit(TypeReferenceNode node);
    T Visit(EnumDefinitionNode node);
    T Visit(EnumMemberNode node);
    T Visit(EnumExtensionNode node);
    T Visit(RecordCreationNode node);
    T Visit(FieldAssignmentNode node);
    T Visit(FieldAccessNode node);
    T Visit(SomeExpressionNode node);
    T Visit(NoneExpressionNode node);
    T Visit(OkExpressionNode node);
    T Visit(ErrExpressionNode node);
    T Visit(MatchExpressionNode node);
    T Visit(MatchStatementNode node);
    T Visit(MatchCaseNode node);
    T Visit(WildcardPatternNode node);
    T Visit(VariablePatternNode node);
    T Visit(LiteralPatternNode node);
    T Visit(SomePatternNode node);
    T Visit(NonePatternNode node);
    T Visit(OkPatternNode node);
    T Visit(ErrPatternNode node);
    T Visit(RequiresNode node);
    T Visit(EnsuresNode node);
    T Visit(InvariantNode node);
    T Visit(UsingDirectiveNode node);
    T Visit(ArrayCreationNode node);
    T Visit(ArrayAccessNode node);
    T Visit(ArrayLengthNode node);
    T Visit(ForeachStatementNode node);
    T Visit(ListCreationNode node);
    T Visit(DictionaryCreationNode node);
    T Visit(KeyValuePairNode node);
    T Visit(SetCreationNode node);
    T Visit(CollectionPushNode node);
    T Visit(DictionaryPutNode node);
    T Visit(CollectionRemoveNode node);
    T Visit(CollectionSetIndexNode node);
    T Visit(CollectionClearNode node);
    T Visit(CollectionInsertNode node);
    T Visit(CollectionContainsNode node);
    T Visit(DictionaryForeachNode node);
    T Visit(CollectionCountNode node);
    T Visit(TypeParameterNode node);
    T Visit(TypeConstraintNode node);
    T Visit(GenericTypeNode node);
    T Visit(InterfaceDefinitionNode node);
    T Visit(MethodSignatureNode node);
    T Visit(ClassDefinitionNode node);
    T Visit(ClassFieldNode node);
    T Visit(MethodNode node);
    T Visit(NewExpressionNode node);
    T Visit(AnonymousObjectCreationNode node);
    T Visit(CallExpressionNode node);
    T Visit(ThisExpressionNode node);
    T Visit(BaseExpressionNode node);
    T Visit(TupleLiteralNode node);
    T Visit(PropertyNode node);
    T Visit(IndexerNode node);
    T Visit(PropertyAccessorNode node);
    T Visit(ConstructorNode node);
    T Visit(OperatorOverloadNode node);
    T Visit(ConstructorInitializerNode node);
    T Visit(AssignmentStatementNode node);
    T Visit(CompoundAssignmentStatementNode node);
    T Visit(UsingStatementNode node);
    T Visit(TryStatementNode node);
    T Visit(CatchClauseNode node);
    T Visit(ThrowStatementNode node);
    T Visit(ThrowExpressionNode node);
    T Visit(RethrowStatementNode node);
    T Visit(LambdaParameterNode node);
    T Visit(LambdaExpressionNode node);
    T Visit(DelegateDefinitionNode node);
    T Visit(EventDefinitionNode node);
    T Visit(EventSubscribeNode node);
    T Visit(EventUnsubscribeNode node);
    T Visit(AwaitExpressionNode node);
    T Visit(InterpolatedStringNode node);
    T Visit(InterpolatedStringTextNode node);
    T Visit(InterpolatedStringExpressionNode node);
    T Visit(NullCoalesceNode node);
    T Visit(NullConditionalNode node);
    T Visit(RangeExpressionNode node);
    T Visit(IndexFromEndNode node);
    T Visit(WithExpressionNode node);
    T Visit(WithPropertyAssignmentNode node);
    T Visit(PositionalPatternNode node);
    T Visit(PropertyPatternNode node);
    T Visit(PropertyMatchNode node);
    T Visit(RelationalPatternNode node);
    T Visit(ListPatternNode node);
    T Visit(VarPatternNode node);
    T Visit(ConstantPatternNode node);
    T Visit(NegatedPatternNode node);
    T Visit(OrPatternNode node);
    T Visit(AndPatternNode node);
    T Visit(TypePatternNode node);
    T Visit(ExampleNode node);
    T Visit(IssueNode node);
    T Visit(DependencyNode node);
    T Visit(UsesNode node);
    T Visit(UsedByNode node);
    T Visit(AssumeNode node);
    T Visit(ComplexityNode node);
    T Visit(SinceNode node);
    T Visit(DeprecatedNode node);
    T Visit(BreakingChangeNode node);
    T Visit(DecisionNode node);
    T Visit(RejectedOptionNode node);
    T Visit(ContextNode node);
    T Visit(FileRefNode node);
    T Visit(PropertyTestNode node);
    T Visit(LockNode node);
    T Visit(AuthorNode node);
    T Visit(TaskRefNode node);
    T Visit(CalorAttributeNode node);
    T Visit(QuantifierVariableNode node);
    T Visit(ForallExpressionNode node);
    T Visit(ExistsExpressionNode node);
    T Visit(ImplicationExpressionNode node);
    T Visit(StringOperationNode node);
    T Visit(CharOperationNode node);
    T Visit(StringBuilderOperationNode node);
    T Visit(TypeOperationNode node);
    T Visit(IsPatternNode node);
    T Visit(ExpressionStatementNode node);
    T Visit(FallbackExpressionNode node);
    T Visit(FallbackCommentNode node);
    T Visit(TypeOfExpressionNode node);
    T Visit(NameOfExpressionNode node);
    T Visit(ExpressionCallNode node);
    T Visit(YieldReturnStatementNode node);
    T Visit(YieldBreakStatementNode node);
    T Visit(RawCSharpNode node);
    T Visit(CompilerDirectiveNode node);
    T Visit(CSharpInteropBlockNode node);
    T Visit(StackAllocNode node);
    T Visit(UnsafeBlockNode node);
    T Visit(FixedStatementNode node);
    T Visit(AddressOfNode node);
    T Visit(PointerDereferenceNode node);
    T Visit(SizeOfNode node);
    T Visit(MultiDimArrayCreationNode node);
    T Visit(MultiDimArrayAccessNode node);
    T Visit(RawCSharpExpressionNode node);
    T Visit(PreprocessorDirectiveNode node);
    T Visit(MemberPreprocessorBlockNode node);
    T Visit(TypePreprocessorBlockNode node);
    T Visit(RefinementTypeNode node);
    T Visit(SelfRefNode node);
    T Visit(ProofObligationNode node);
    T Visit(IndexedTypeNode node);
    T Visit(SyncBlockNode node);
}

public sealed record AstNodeSchemaEntry(
    Type NodeType,
    string SourceFile,
    IReadOnlyList<string> ChildProperties);

public static class AstSchemaMetadata
{
    public static IReadOnlyList<AstNodeSchemaEntry> Nodes { get; } =
    [
        Create<ModuleNode>("ModuleNode.cs"),
        Create<FunctionNode>("FunctionNode.cs"),
        Create<OutputNode>("FunctionNode.cs"),
        Create<EffectsNode>("FunctionNode.cs"),
        Create<ParameterNode>("FunctionNode.cs"),
        Create<CallStatementNode>("StatementNodes.cs"),
        Create<ReturnStatementNode>("StatementNodes.cs"),
        Create<IntLiteralNode>("ExpressionNodes.cs"),
        Create<StringLiteralNode>("ExpressionNodes.cs"),
        Create<BoolLiteralNode>("ExpressionNodes.cs"),
        Create<ConditionalExpressionNode>("ExpressionNodes.cs"),
        Create<FloatLiteralNode>("ExpressionNodes.cs"),
        Create<DecimalLiteralNode>("ExpressionNodes.cs"),
        Create<ReferenceNode>("ExpressionNodes.cs"),
        Create<ForStatementNode>("ControlFlowNodes.cs"),
        Create<WhileStatementNode>("ControlFlowNodes.cs"),
        Create<DoWhileStatementNode>("ControlFlowNodes.cs"),
        Create<IfStatementNode>("ControlFlowNodes.cs"),
        Create<ElseIfClauseNode>("ControlFlowNodes.cs"),
        Create<BindStatementNode>("ControlFlowNodes.cs"),
        Create<BinaryOperationNode>("ControlFlowNodes.cs"),
        Create<UnaryOperationNode>("ExpressionNodes.cs"),
        Create<ContinueStatementNode>("ControlFlowNodes.cs"),
        Create<BreakStatementNode>("ControlFlowNodes.cs"),
        Create<GotoStatementNode>("ControlFlowNodes.cs"),
        Create<LabelStatementNode>("ControlFlowNodes.cs"),
        Create<PrintStatementNode>("StatementNodes.cs"),
        Create<RecordDefinitionNode>("TypeNodes.cs"),
        Create<FieldDefinitionNode>("TypeNodes.cs"),
        Create<UnionTypeDefinitionNode>("TypeNodes.cs"),
        Create<VariantDefinitionNode>("TypeNodes.cs"),
        Create<TypeReferenceNode>("TypeNodes.cs"),
        Create<EnumDefinitionNode>("TypeNodes.cs"),
        Create<EnumMemberNode>("TypeNodes.cs"),
        Create<EnumExtensionNode>("EnumExtensionNode.cs"),
        Create<RecordCreationNode>("TypeNodes.cs"),
        Create<FieldAssignmentNode>("TypeNodes.cs"),
        Create<FieldAccessNode>("TypeNodes.cs"),
        Create<SomeExpressionNode>("TypeNodes.cs"),
        Create<NoneExpressionNode>("TypeNodes.cs"),
        Create<OkExpressionNode>("TypeNodes.cs"),
        Create<ErrExpressionNode>("TypeNodes.cs"),
        Create<MatchExpressionNode>("PatternNodes.cs"),
        Create<MatchStatementNode>("PatternNodes.cs"),
        Create<MatchCaseNode>("PatternNodes.cs"),
        Create<WildcardPatternNode>("PatternNodes.cs"),
        Create<VariablePatternNode>("PatternNodes.cs"),
        Create<LiteralPatternNode>("PatternNodes.cs"),
        Create<SomePatternNode>("PatternNodes.cs"),
        Create<NonePatternNode>("PatternNodes.cs"),
        Create<OkPatternNode>("PatternNodes.cs"),
        Create<ErrPatternNode>("PatternNodes.cs"),
        Create<RequiresNode>("ContractNodes.cs"),
        Create<EnsuresNode>("ContractNodes.cs"),
        Create<InvariantNode>("ContractNodes.cs"),
        Create<UsingDirectiveNode>("UsingDirectiveNode.cs"),
        Create<ArrayCreationNode>("ArrayNodes.cs"),
        Create<ArrayAccessNode>("ArrayNodes.cs"),
        Create<ArrayLengthNode>("ArrayNodes.cs"),
        Create<ForeachStatementNode>("ArrayNodes.cs"),
        Create<ListCreationNode>("CollectionNodes.cs"),
        Create<DictionaryCreationNode>("CollectionNodes.cs"),
        Create<KeyValuePairNode>("CollectionNodes.cs"),
        Create<SetCreationNode>("CollectionNodes.cs"),
        Create<CollectionPushNode>("CollectionNodes.cs"),
        Create<DictionaryPutNode>("CollectionNodes.cs"),
        Create<CollectionRemoveNode>("CollectionNodes.cs"),
        Create<CollectionSetIndexNode>("CollectionNodes.cs"),
        Create<CollectionClearNode>("CollectionNodes.cs"),
        Create<CollectionInsertNode>("CollectionNodes.cs"),
        Create<CollectionContainsNode>("CollectionNodes.cs"),
        Create<DictionaryForeachNode>("CollectionNodes.cs"),
        Create<CollectionCountNode>("CollectionNodes.cs"),
        Create<TypeParameterNode>("GenericNodes.cs"),
        Create<TypeConstraintNode>("GenericNodes.cs"),
        Create<GenericTypeNode>("GenericNodes.cs"),
        Create<InterfaceDefinitionNode>("ClassNodes.cs"),
        Create<MethodSignatureNode>("ClassNodes.cs"),
        Create<ClassDefinitionNode>("ClassNodes.cs"),
        Create<ClassFieldNode>("ClassNodes.cs"),
        Create<MethodNode>("ClassNodes.cs"),
        Create<NewExpressionNode>("ClassNodes.cs"),
        Create<AnonymousObjectCreationNode>("ClassNodes.cs"),
        Create<CallExpressionNode>("ClassNodes.cs"),
        Create<ThisExpressionNode>("ClassNodes.cs"),
        Create<BaseExpressionNode>("ClassNodes.cs"),
        Create<TupleLiteralNode>("ClassNodes.cs"),
        Create<PropertyNode>("PropertyNodes.cs"),
        Create<IndexerNode>("PropertyNodes.cs"),
        Create<PropertyAccessorNode>("PropertyNodes.cs"),
        Create<ConstructorNode>("PropertyNodes.cs"),
        Create<OperatorOverloadNode>("ClassNodes.cs"),
        Create<ConstructorInitializerNode>("PropertyNodes.cs"),
        Create<AssignmentStatementNode>("PropertyNodes.cs"),
        Create<CompoundAssignmentStatementNode>("PropertyNodes.cs"),
        Create<UsingStatementNode>("PropertyNodes.cs"),
        Create<TryStatementNode>("ExceptionNodes.cs"),
        Create<CatchClauseNode>("ExceptionNodes.cs"),
        Create<ThrowStatementNode>("ExceptionNodes.cs"),
        Create<ThrowExpressionNode>("ExceptionNodes.cs"),
        Create<RethrowStatementNode>("ExceptionNodes.cs"),
        Create<LambdaParameterNode>("LambdaNodes.cs"),
        Create<LambdaExpressionNode>("LambdaNodes.cs"),
        Create<DelegateDefinitionNode>("LambdaNodes.cs"),
        Create<EventDefinitionNode>("LambdaNodes.cs"),
        Create<EventSubscribeNode>("LambdaNodes.cs"),
        Create<EventUnsubscribeNode>("LambdaNodes.cs"),
        Create<AwaitExpressionNode>("AsyncNodes.cs"),
        Create<InterpolatedStringNode>("ModernOperatorNodes.cs"),
        Create<InterpolatedStringTextNode>("ModernOperatorNodes.cs"),
        Create<InterpolatedStringExpressionNode>("ModernOperatorNodes.cs"),
        Create<NullCoalesceNode>("ModernOperatorNodes.cs"),
        Create<NullConditionalNode>("ModernOperatorNodes.cs"),
        Create<RangeExpressionNode>("ModernOperatorNodes.cs"),
        Create<IndexFromEndNode>("ModernOperatorNodes.cs"),
        Create<WithExpressionNode>("PatternNodes.cs"),
        Create<WithPropertyAssignmentNode>("PatternNodes.cs"),
        Create<PositionalPatternNode>("PatternNodes.cs"),
        Create<PropertyPatternNode>("PatternNodes.cs"),
        Create<PropertyMatchNode>("PatternNodes.cs"),
        Create<RelationalPatternNode>("PatternNodes.cs"),
        Create<ListPatternNode>("PatternNodes.cs"),
        Create<VarPatternNode>("PatternNodes.cs"),
        Create<ConstantPatternNode>("PatternNodes.cs"),
        Create<NegatedPatternNode>("PatternNodes.cs"),
        Create<OrPatternNode>("PatternNodes.cs"),
        Create<AndPatternNode>("PatternNodes.cs"),
        Create<TypePatternNode>("PatternNodes.cs"),
        Create<ExampleNode>("MetadataNodes.cs"),
        Create<IssueNode>("MetadataNodes.cs"),
        Create<DependencyNode>("MetadataNodes.cs"),
        Create<UsesNode>("MetadataNodes.cs"),
        Create<UsedByNode>("MetadataNodes.cs"),
        Create<AssumeNode>("MetadataNodes.cs"),
        Create<ComplexityNode>("MetadataNodes.cs"),
        Create<SinceNode>("MetadataNodes.cs"),
        Create<DeprecatedNode>("MetadataNodes.cs"),
        Create<BreakingChangeNode>("MetadataNodes.cs"),
        Create<DecisionNode>("MetadataNodes.cs"),
        Create<RejectedOptionNode>("MetadataNodes.cs"),
        Create<ContextNode>("MetadataNodes.cs"),
        Create<FileRefNode>("MetadataNodes.cs"),
        Create<PropertyTestNode>("MetadataNodes.cs"),
        Create<LockNode>("MetadataNodes.cs"),
        Create<AuthorNode>("MetadataNodes.cs"),
        Create<TaskRefNode>("MetadataNodes.cs"),
        Create<CalorAttributeNode>("AttributeNodes.cs"),
        Create<QuantifierVariableNode>("QuantifierNodes.cs"),
        Create<ForallExpressionNode>("QuantifierNodes.cs"),
        Create<ExistsExpressionNode>("QuantifierNodes.cs"),
        Create<ImplicationExpressionNode>("QuantifierNodes.cs"),
        Create<StringOperationNode>("StringOperationNode.cs"),
        Create<CharOperationNode>("CharOperationNode.cs"),
        Create<StringBuilderOperationNode>("StringBuilderOperationNode.cs"),
        Create<TypeOperationNode>("TypeOperationNode.cs"),
        Create<IsPatternNode>("TypeOperationNode.cs"),
        Create<ExpressionStatementNode>("StatementNodes.cs"),
        Create<FallbackExpressionNode>("ExpressionNodes.cs"),
        Create<FallbackCommentNode>("StatementNodes.cs"),
        Create<TypeOfExpressionNode>("ModernOperatorNodes.cs"),
        Create<NameOfExpressionNode>("ModernOperatorNodes.cs"),
        Create<ExpressionCallNode>("ModernOperatorNodes.cs"),
        Create<YieldReturnStatementNode>("ControlFlowNodes.cs"),
        Create<YieldBreakStatementNode>("ControlFlowNodes.cs"),
        Create<RawCSharpNode>("StatementNodes.cs"),
        Create<CompilerDirectiveNode>("StatementNodes.cs"),
        Create<CSharpInteropBlockNode>("StatementNodes.cs"),
        Create<StackAllocNode>("UnsafeNodes.cs"),
        Create<UnsafeBlockNode>("UnsafeNodes.cs"),
        Create<FixedStatementNode>("UnsafeNodes.cs"),
        Create<AddressOfNode>("UnsafeNodes.cs"),
        Create<PointerDereferenceNode>("UnsafeNodes.cs"),
        Create<SizeOfNode>("UnsafeNodes.cs"),
        Create<MultiDimArrayCreationNode>("ArrayNodes.cs"),
        Create<MultiDimArrayAccessNode>("ArrayNodes.cs"),
        Create<RawCSharpExpressionNode>("ExpressionNodes.cs"),
        Create<PreprocessorDirectiveNode>("StatementNodes.cs"),
        Create<MemberPreprocessorBlockNode>("StatementNodes.cs"),
        Create<TypePreprocessorBlockNode>("StatementNodes.cs"),
        Create<RefinementTypeNode>("RefinementNodes.cs"),
        Create<SelfRefNode>("RefinementNodes.cs"),
        Create<ProofObligationNode>("RefinementNodes.cs"),
        Create<IndexedTypeNode>("RefinementNodes.cs"),
        Create<SyncBlockNode>("UnsafeNodes.cs"),
    ];

    public static IReadOnlyList<Type> NodeTypes { get; } =
        Nodes.Select(node => node.NodeType).ToArray();

    private static AstNodeSchemaEntry Create<TNode>(string sourceFile)
        where TNode : AstNode
        => new(
            typeof(TNode),
            sourceFile,
            typeof(TNode)
                .GetProperties(System.Reflection.BindingFlags.Public |
                    System.Reflection.BindingFlags.Instance)
                .Where(property => property.GetIndexParameters().Length == 0)
                .Where(property => CanContainAstNode(property.PropertyType))
                .Select(property => property.Name)
                .OrderBy(name => name, StringComparer.Ordinal)
                .ToArray());

    private static bool CanContainAstNode(Type type)
    {
        if (typeof(AstNode).IsAssignableFrom(type))
            return true;
        if (type == typeof(string))
            return false;
        return type.GetInterfaces()
            .Prepend(type)
            .Where(candidate => candidate.IsGenericType)
            .Where(candidate =>
                candidate.GetGenericTypeDefinition() == typeof(IEnumerable<>))
            .Select(candidate => candidate.GetGenericArguments()[0])
            .Any(typeof(AstNode).IsAssignableFrom);
    }
}

internal static class AstVisitorDispatch
{
    public static void Visit(IAstVisitor visitor, AstNode node)
    {
        ArgumentNullException.ThrowIfNull(visitor);
        ArgumentNullException.ThrowIfNull(node);
        switch (node)
        {
            case ModuleNode typed: visitor.Visit(typed); return;
            case FunctionNode typed: visitor.Visit(typed); return;
            case OutputNode typed: visitor.Visit(typed); return;
            case EffectsNode typed: visitor.Visit(typed); return;
            case ParameterNode typed: visitor.Visit(typed); return;
            case CallStatementNode typed: visitor.Visit(typed); return;
            case ReturnStatementNode typed: visitor.Visit(typed); return;
            case IntLiteralNode typed: visitor.Visit(typed); return;
            case StringLiteralNode typed: visitor.Visit(typed); return;
            case BoolLiteralNode typed: visitor.Visit(typed); return;
            case ConditionalExpressionNode typed: visitor.Visit(typed); return;
            case FloatLiteralNode typed: visitor.Visit(typed); return;
            case DecimalLiteralNode typed: visitor.Visit(typed); return;
            case ReferenceNode typed: visitor.Visit(typed); return;
            case ForStatementNode typed: visitor.Visit(typed); return;
            case WhileStatementNode typed: visitor.Visit(typed); return;
            case DoWhileStatementNode typed: visitor.Visit(typed); return;
            case IfStatementNode typed: visitor.Visit(typed); return;
            case ElseIfClauseNode typed: visitor.Visit(typed); return;
            case BindStatementNode typed: visitor.Visit(typed); return;
            case BinaryOperationNode typed: visitor.Visit(typed); return;
            case UnaryOperationNode typed: visitor.Visit(typed); return;
            case ContinueStatementNode typed: visitor.Visit(typed); return;
            case BreakStatementNode typed: visitor.Visit(typed); return;
            case GotoStatementNode typed: visitor.Visit(typed); return;
            case LabelStatementNode typed: visitor.Visit(typed); return;
            case PrintStatementNode typed: visitor.Visit(typed); return;
            case RecordDefinitionNode typed: visitor.Visit(typed); return;
            case FieldDefinitionNode typed: visitor.Visit(typed); return;
            case UnionTypeDefinitionNode typed: visitor.Visit(typed); return;
            case VariantDefinitionNode typed: visitor.Visit(typed); return;
            case TypeReferenceNode typed: visitor.Visit(typed); return;
            case EnumDefinitionNode typed: visitor.Visit(typed); return;
            case EnumMemberNode typed: visitor.Visit(typed); return;
            case EnumExtensionNode typed: visitor.Visit(typed); return;
            case RecordCreationNode typed: visitor.Visit(typed); return;
            case FieldAssignmentNode typed: visitor.Visit(typed); return;
            case FieldAccessNode typed: visitor.Visit(typed); return;
            case SomeExpressionNode typed: visitor.Visit(typed); return;
            case NoneExpressionNode typed: visitor.Visit(typed); return;
            case OkExpressionNode typed: visitor.Visit(typed); return;
            case ErrExpressionNode typed: visitor.Visit(typed); return;
            case MatchExpressionNode typed: visitor.Visit(typed); return;
            case MatchStatementNode typed: visitor.Visit(typed); return;
            case MatchCaseNode typed: visitor.Visit(typed); return;
            case WildcardPatternNode typed: visitor.Visit(typed); return;
            case VariablePatternNode typed: visitor.Visit(typed); return;
            case LiteralPatternNode typed: visitor.Visit(typed); return;
            case SomePatternNode typed: visitor.Visit(typed); return;
            case NonePatternNode typed: visitor.Visit(typed); return;
            case OkPatternNode typed: visitor.Visit(typed); return;
            case ErrPatternNode typed: visitor.Visit(typed); return;
            case RequiresNode typed: visitor.Visit(typed); return;
            case EnsuresNode typed: visitor.Visit(typed); return;
            case InvariantNode typed: visitor.Visit(typed); return;
            case UsingDirectiveNode typed: visitor.Visit(typed); return;
            case ArrayCreationNode typed: visitor.Visit(typed); return;
            case ArrayAccessNode typed: visitor.Visit(typed); return;
            case ArrayLengthNode typed: visitor.Visit(typed); return;
            case ForeachStatementNode typed: visitor.Visit(typed); return;
            case ListCreationNode typed: visitor.Visit(typed); return;
            case DictionaryCreationNode typed: visitor.Visit(typed); return;
            case KeyValuePairNode typed: visitor.Visit(typed); return;
            case SetCreationNode typed: visitor.Visit(typed); return;
            case CollectionPushNode typed: visitor.Visit(typed); return;
            case DictionaryPutNode typed: visitor.Visit(typed); return;
            case CollectionRemoveNode typed: visitor.Visit(typed); return;
            case CollectionSetIndexNode typed: visitor.Visit(typed); return;
            case CollectionClearNode typed: visitor.Visit(typed); return;
            case CollectionInsertNode typed: visitor.Visit(typed); return;
            case CollectionContainsNode typed: visitor.Visit(typed); return;
            case DictionaryForeachNode typed: visitor.Visit(typed); return;
            case CollectionCountNode typed: visitor.Visit(typed); return;
            case TypeParameterNode typed: visitor.Visit(typed); return;
            case TypeConstraintNode typed: visitor.Visit(typed); return;
            case GenericTypeNode typed: visitor.Visit(typed); return;
            case InterfaceDefinitionNode typed: visitor.Visit(typed); return;
            case MethodSignatureNode typed: visitor.Visit(typed); return;
            case ClassDefinitionNode typed: visitor.Visit(typed); return;
            case ClassFieldNode typed: visitor.Visit(typed); return;
            case MethodNode typed: visitor.Visit(typed); return;
            case NewExpressionNode typed: visitor.Visit(typed); return;
            case AnonymousObjectCreationNode typed: visitor.Visit(typed); return;
            case CallExpressionNode typed: visitor.Visit(typed); return;
            case ThisExpressionNode typed: visitor.Visit(typed); return;
            case BaseExpressionNode typed: visitor.Visit(typed); return;
            case TupleLiteralNode typed: visitor.Visit(typed); return;
            case PropertyNode typed: visitor.Visit(typed); return;
            case IndexerNode typed: visitor.Visit(typed); return;
            case PropertyAccessorNode typed: visitor.Visit(typed); return;
            case ConstructorNode typed: visitor.Visit(typed); return;
            case OperatorOverloadNode typed: visitor.Visit(typed); return;
            case ConstructorInitializerNode typed: visitor.Visit(typed); return;
            case AssignmentStatementNode typed: visitor.Visit(typed); return;
            case CompoundAssignmentStatementNode typed: visitor.Visit(typed); return;
            case UsingStatementNode typed: visitor.Visit(typed); return;
            case TryStatementNode typed: visitor.Visit(typed); return;
            case CatchClauseNode typed: visitor.Visit(typed); return;
            case ThrowStatementNode typed: visitor.Visit(typed); return;
            case ThrowExpressionNode typed: visitor.Visit(typed); return;
            case RethrowStatementNode typed: visitor.Visit(typed); return;
            case LambdaParameterNode typed: visitor.Visit(typed); return;
            case LambdaExpressionNode typed: visitor.Visit(typed); return;
            case DelegateDefinitionNode typed: visitor.Visit(typed); return;
            case EventDefinitionNode typed: visitor.Visit(typed); return;
            case EventSubscribeNode typed: visitor.Visit(typed); return;
            case EventUnsubscribeNode typed: visitor.Visit(typed); return;
            case AwaitExpressionNode typed: visitor.Visit(typed); return;
            case InterpolatedStringNode typed: visitor.Visit(typed); return;
            case InterpolatedStringTextNode typed: visitor.Visit(typed); return;
            case InterpolatedStringExpressionNode typed: visitor.Visit(typed); return;
            case NullCoalesceNode typed: visitor.Visit(typed); return;
            case NullConditionalNode typed: visitor.Visit(typed); return;
            case RangeExpressionNode typed: visitor.Visit(typed); return;
            case IndexFromEndNode typed: visitor.Visit(typed); return;
            case WithExpressionNode typed: visitor.Visit(typed); return;
            case WithPropertyAssignmentNode typed: visitor.Visit(typed); return;
            case PositionalPatternNode typed: visitor.Visit(typed); return;
            case PropertyPatternNode typed: visitor.Visit(typed); return;
            case PropertyMatchNode typed: visitor.Visit(typed); return;
            case RelationalPatternNode typed: visitor.Visit(typed); return;
            case ListPatternNode typed: visitor.Visit(typed); return;
            case VarPatternNode typed: visitor.Visit(typed); return;
            case ConstantPatternNode typed: visitor.Visit(typed); return;
            case NegatedPatternNode typed: visitor.Visit(typed); return;
            case OrPatternNode typed: visitor.Visit(typed); return;
            case AndPatternNode typed: visitor.Visit(typed); return;
            case TypePatternNode typed: visitor.Visit(typed); return;
            case ExampleNode typed: visitor.Visit(typed); return;
            case IssueNode typed: visitor.Visit(typed); return;
            case DependencyNode typed: visitor.Visit(typed); return;
            case UsesNode typed: visitor.Visit(typed); return;
            case UsedByNode typed: visitor.Visit(typed); return;
            case AssumeNode typed: visitor.Visit(typed); return;
            case ComplexityNode typed: visitor.Visit(typed); return;
            case SinceNode typed: visitor.Visit(typed); return;
            case DeprecatedNode typed: visitor.Visit(typed); return;
            case BreakingChangeNode typed: visitor.Visit(typed); return;
            case DecisionNode typed: visitor.Visit(typed); return;
            case RejectedOptionNode typed: visitor.Visit(typed); return;
            case ContextNode typed: visitor.Visit(typed); return;
            case FileRefNode typed: visitor.Visit(typed); return;
            case PropertyTestNode typed: visitor.Visit(typed); return;
            case LockNode typed: visitor.Visit(typed); return;
            case AuthorNode typed: visitor.Visit(typed); return;
            case TaskRefNode typed: visitor.Visit(typed); return;
            case CalorAttributeNode typed: visitor.Visit(typed); return;
            case QuantifierVariableNode typed: visitor.Visit(typed); return;
            case ForallExpressionNode typed: visitor.Visit(typed); return;
            case ExistsExpressionNode typed: visitor.Visit(typed); return;
            case ImplicationExpressionNode typed: visitor.Visit(typed); return;
            case StringOperationNode typed: visitor.Visit(typed); return;
            case CharOperationNode typed: visitor.Visit(typed); return;
            case StringBuilderOperationNode typed: visitor.Visit(typed); return;
            case TypeOperationNode typed: visitor.Visit(typed); return;
            case IsPatternNode typed: visitor.Visit(typed); return;
            case ExpressionStatementNode typed: visitor.Visit(typed); return;
            case FallbackExpressionNode typed: visitor.Visit(typed); return;
            case FallbackCommentNode typed: visitor.Visit(typed); return;
            case TypeOfExpressionNode typed: visitor.Visit(typed); return;
            case NameOfExpressionNode typed: visitor.Visit(typed); return;
            case ExpressionCallNode typed: visitor.Visit(typed); return;
            case YieldReturnStatementNode typed: visitor.Visit(typed); return;
            case YieldBreakStatementNode typed: visitor.Visit(typed); return;
            case RawCSharpNode typed: visitor.Visit(typed); return;
            case CompilerDirectiveNode typed: visitor.Visit(typed); return;
            case CSharpInteropBlockNode typed: visitor.Visit(typed); return;
            case StackAllocNode typed: visitor.Visit(typed); return;
            case UnsafeBlockNode typed: visitor.Visit(typed); return;
            case FixedStatementNode typed: visitor.Visit(typed); return;
            case AddressOfNode typed: visitor.Visit(typed); return;
            case PointerDereferenceNode typed: visitor.Visit(typed); return;
            case SizeOfNode typed: visitor.Visit(typed); return;
            case MultiDimArrayCreationNode typed: visitor.Visit(typed); return;
            case MultiDimArrayAccessNode typed: visitor.Visit(typed); return;
            case RawCSharpExpressionNode typed: visitor.Visit(typed); return;
            case PreprocessorDirectiveNode typed: visitor.Visit(typed); return;
            case MemberPreprocessorBlockNode typed: visitor.Visit(typed); return;
            case TypePreprocessorBlockNode typed: visitor.Visit(typed); return;
            case RefinementTypeNode typed: visitor.Visit(typed); return;
            case SelfRefNode typed: visitor.Visit(typed); return;
            case ProofObligationNode typed: visitor.Visit(typed); return;
            case IndexedTypeNode typed: visitor.Visit(typed); return;
            case SyncBlockNode typed: visitor.Visit(typed); return;
            default:
                throw new InvalidOperationException(
                    $"AST node '{node.GetType().FullName}' is absent from eng/ast-schema.json.");
        }
    }

    public static T Visit<T>(IAstVisitor<T> visitor, AstNode node)
    {
        ArgumentNullException.ThrowIfNull(visitor);
        ArgumentNullException.ThrowIfNull(node);
        return node switch
        {
            ModuleNode typed => visitor.Visit(typed),
            FunctionNode typed => visitor.Visit(typed),
            OutputNode typed => visitor.Visit(typed),
            EffectsNode typed => visitor.Visit(typed),
            ParameterNode typed => visitor.Visit(typed),
            CallStatementNode typed => visitor.Visit(typed),
            ReturnStatementNode typed => visitor.Visit(typed),
            IntLiteralNode typed => visitor.Visit(typed),
            StringLiteralNode typed => visitor.Visit(typed),
            BoolLiteralNode typed => visitor.Visit(typed),
            ConditionalExpressionNode typed => visitor.Visit(typed),
            FloatLiteralNode typed => visitor.Visit(typed),
            DecimalLiteralNode typed => visitor.Visit(typed),
            ReferenceNode typed => visitor.Visit(typed),
            ForStatementNode typed => visitor.Visit(typed),
            WhileStatementNode typed => visitor.Visit(typed),
            DoWhileStatementNode typed => visitor.Visit(typed),
            IfStatementNode typed => visitor.Visit(typed),
            ElseIfClauseNode typed => visitor.Visit(typed),
            BindStatementNode typed => visitor.Visit(typed),
            BinaryOperationNode typed => visitor.Visit(typed),
            UnaryOperationNode typed => visitor.Visit(typed),
            ContinueStatementNode typed => visitor.Visit(typed),
            BreakStatementNode typed => visitor.Visit(typed),
            GotoStatementNode typed => visitor.Visit(typed),
            LabelStatementNode typed => visitor.Visit(typed),
            PrintStatementNode typed => visitor.Visit(typed),
            RecordDefinitionNode typed => visitor.Visit(typed),
            FieldDefinitionNode typed => visitor.Visit(typed),
            UnionTypeDefinitionNode typed => visitor.Visit(typed),
            VariantDefinitionNode typed => visitor.Visit(typed),
            TypeReferenceNode typed => visitor.Visit(typed),
            EnumDefinitionNode typed => visitor.Visit(typed),
            EnumMemberNode typed => visitor.Visit(typed),
            EnumExtensionNode typed => visitor.Visit(typed),
            RecordCreationNode typed => visitor.Visit(typed),
            FieldAssignmentNode typed => visitor.Visit(typed),
            FieldAccessNode typed => visitor.Visit(typed),
            SomeExpressionNode typed => visitor.Visit(typed),
            NoneExpressionNode typed => visitor.Visit(typed),
            OkExpressionNode typed => visitor.Visit(typed),
            ErrExpressionNode typed => visitor.Visit(typed),
            MatchExpressionNode typed => visitor.Visit(typed),
            MatchStatementNode typed => visitor.Visit(typed),
            MatchCaseNode typed => visitor.Visit(typed),
            WildcardPatternNode typed => visitor.Visit(typed),
            VariablePatternNode typed => visitor.Visit(typed),
            LiteralPatternNode typed => visitor.Visit(typed),
            SomePatternNode typed => visitor.Visit(typed),
            NonePatternNode typed => visitor.Visit(typed),
            OkPatternNode typed => visitor.Visit(typed),
            ErrPatternNode typed => visitor.Visit(typed),
            RequiresNode typed => visitor.Visit(typed),
            EnsuresNode typed => visitor.Visit(typed),
            InvariantNode typed => visitor.Visit(typed),
            UsingDirectiveNode typed => visitor.Visit(typed),
            ArrayCreationNode typed => visitor.Visit(typed),
            ArrayAccessNode typed => visitor.Visit(typed),
            ArrayLengthNode typed => visitor.Visit(typed),
            ForeachStatementNode typed => visitor.Visit(typed),
            ListCreationNode typed => visitor.Visit(typed),
            DictionaryCreationNode typed => visitor.Visit(typed),
            KeyValuePairNode typed => visitor.Visit(typed),
            SetCreationNode typed => visitor.Visit(typed),
            CollectionPushNode typed => visitor.Visit(typed),
            DictionaryPutNode typed => visitor.Visit(typed),
            CollectionRemoveNode typed => visitor.Visit(typed),
            CollectionSetIndexNode typed => visitor.Visit(typed),
            CollectionClearNode typed => visitor.Visit(typed),
            CollectionInsertNode typed => visitor.Visit(typed),
            CollectionContainsNode typed => visitor.Visit(typed),
            DictionaryForeachNode typed => visitor.Visit(typed),
            CollectionCountNode typed => visitor.Visit(typed),
            TypeParameterNode typed => visitor.Visit(typed),
            TypeConstraintNode typed => visitor.Visit(typed),
            GenericTypeNode typed => visitor.Visit(typed),
            InterfaceDefinitionNode typed => visitor.Visit(typed),
            MethodSignatureNode typed => visitor.Visit(typed),
            ClassDefinitionNode typed => visitor.Visit(typed),
            ClassFieldNode typed => visitor.Visit(typed),
            MethodNode typed => visitor.Visit(typed),
            NewExpressionNode typed => visitor.Visit(typed),
            AnonymousObjectCreationNode typed => visitor.Visit(typed),
            CallExpressionNode typed => visitor.Visit(typed),
            ThisExpressionNode typed => visitor.Visit(typed),
            BaseExpressionNode typed => visitor.Visit(typed),
            TupleLiteralNode typed => visitor.Visit(typed),
            PropertyNode typed => visitor.Visit(typed),
            IndexerNode typed => visitor.Visit(typed),
            PropertyAccessorNode typed => visitor.Visit(typed),
            ConstructorNode typed => visitor.Visit(typed),
            OperatorOverloadNode typed => visitor.Visit(typed),
            ConstructorInitializerNode typed => visitor.Visit(typed),
            AssignmentStatementNode typed => visitor.Visit(typed),
            CompoundAssignmentStatementNode typed => visitor.Visit(typed),
            UsingStatementNode typed => visitor.Visit(typed),
            TryStatementNode typed => visitor.Visit(typed),
            CatchClauseNode typed => visitor.Visit(typed),
            ThrowStatementNode typed => visitor.Visit(typed),
            ThrowExpressionNode typed => visitor.Visit(typed),
            RethrowStatementNode typed => visitor.Visit(typed),
            LambdaParameterNode typed => visitor.Visit(typed),
            LambdaExpressionNode typed => visitor.Visit(typed),
            DelegateDefinitionNode typed => visitor.Visit(typed),
            EventDefinitionNode typed => visitor.Visit(typed),
            EventSubscribeNode typed => visitor.Visit(typed),
            EventUnsubscribeNode typed => visitor.Visit(typed),
            AwaitExpressionNode typed => visitor.Visit(typed),
            InterpolatedStringNode typed => visitor.Visit(typed),
            InterpolatedStringTextNode typed => visitor.Visit(typed),
            InterpolatedStringExpressionNode typed => visitor.Visit(typed),
            NullCoalesceNode typed => visitor.Visit(typed),
            NullConditionalNode typed => visitor.Visit(typed),
            RangeExpressionNode typed => visitor.Visit(typed),
            IndexFromEndNode typed => visitor.Visit(typed),
            WithExpressionNode typed => visitor.Visit(typed),
            WithPropertyAssignmentNode typed => visitor.Visit(typed),
            PositionalPatternNode typed => visitor.Visit(typed),
            PropertyPatternNode typed => visitor.Visit(typed),
            PropertyMatchNode typed => visitor.Visit(typed),
            RelationalPatternNode typed => visitor.Visit(typed),
            ListPatternNode typed => visitor.Visit(typed),
            VarPatternNode typed => visitor.Visit(typed),
            ConstantPatternNode typed => visitor.Visit(typed),
            NegatedPatternNode typed => visitor.Visit(typed),
            OrPatternNode typed => visitor.Visit(typed),
            AndPatternNode typed => visitor.Visit(typed),
            TypePatternNode typed => visitor.Visit(typed),
            ExampleNode typed => visitor.Visit(typed),
            IssueNode typed => visitor.Visit(typed),
            DependencyNode typed => visitor.Visit(typed),
            UsesNode typed => visitor.Visit(typed),
            UsedByNode typed => visitor.Visit(typed),
            AssumeNode typed => visitor.Visit(typed),
            ComplexityNode typed => visitor.Visit(typed),
            SinceNode typed => visitor.Visit(typed),
            DeprecatedNode typed => visitor.Visit(typed),
            BreakingChangeNode typed => visitor.Visit(typed),
            DecisionNode typed => visitor.Visit(typed),
            RejectedOptionNode typed => visitor.Visit(typed),
            ContextNode typed => visitor.Visit(typed),
            FileRefNode typed => visitor.Visit(typed),
            PropertyTestNode typed => visitor.Visit(typed),
            LockNode typed => visitor.Visit(typed),
            AuthorNode typed => visitor.Visit(typed),
            TaskRefNode typed => visitor.Visit(typed),
            CalorAttributeNode typed => visitor.Visit(typed),
            QuantifierVariableNode typed => visitor.Visit(typed),
            ForallExpressionNode typed => visitor.Visit(typed),
            ExistsExpressionNode typed => visitor.Visit(typed),
            ImplicationExpressionNode typed => visitor.Visit(typed),
            StringOperationNode typed => visitor.Visit(typed),
            CharOperationNode typed => visitor.Visit(typed),
            StringBuilderOperationNode typed => visitor.Visit(typed),
            TypeOperationNode typed => visitor.Visit(typed),
            IsPatternNode typed => visitor.Visit(typed),
            ExpressionStatementNode typed => visitor.Visit(typed),
            FallbackExpressionNode typed => visitor.Visit(typed),
            FallbackCommentNode typed => visitor.Visit(typed),
            TypeOfExpressionNode typed => visitor.Visit(typed),
            NameOfExpressionNode typed => visitor.Visit(typed),
            ExpressionCallNode typed => visitor.Visit(typed),
            YieldReturnStatementNode typed => visitor.Visit(typed),
            YieldBreakStatementNode typed => visitor.Visit(typed),
            RawCSharpNode typed => visitor.Visit(typed),
            CompilerDirectiveNode typed => visitor.Visit(typed),
            CSharpInteropBlockNode typed => visitor.Visit(typed),
            StackAllocNode typed => visitor.Visit(typed),
            UnsafeBlockNode typed => visitor.Visit(typed),
            FixedStatementNode typed => visitor.Visit(typed),
            AddressOfNode typed => visitor.Visit(typed),
            PointerDereferenceNode typed => visitor.Visit(typed),
            SizeOfNode typed => visitor.Visit(typed),
            MultiDimArrayCreationNode typed => visitor.Visit(typed),
            MultiDimArrayAccessNode typed => visitor.Visit(typed),
            RawCSharpExpressionNode typed => visitor.Visit(typed),
            PreprocessorDirectiveNode typed => visitor.Visit(typed),
            MemberPreprocessorBlockNode typed => visitor.Visit(typed),
            TypePreprocessorBlockNode typed => visitor.Visit(typed),
            RefinementTypeNode typed => visitor.Visit(typed),
            SelfRefNode typed => visitor.Visit(typed),
            ProofObligationNode typed => visitor.Visit(typed),
            IndexedTypeNode typed => visitor.Visit(typed),
            SyncBlockNode typed => visitor.Visit(typed),
            _ => throw new InvalidOperationException(
                $"AST node '{node.GetType().FullName}' is absent from eng/ast-schema.json.")
        };
    }
}
// </generated-ast-infrastructure>

/// <summary>
/// Represents a collection of key-value attributes on a tag.
/// </summary>
public sealed class AttributeCollection
{
    private readonly Dictionary<string, string> _attributes = new(StringComparer.Ordinal);
    private readonly Dictionary<string, TextSpan> _spans = new(StringComparer.Ordinal);

    public string? this[string key]
        => _attributes.TryGetValue(key, out var value) ? value : null;

    public void Add(string key, string value)
    {
        _attributes[key] = value;
    }

    public void Add(string key, string value, TextSpan span)
    {
        _attributes[key] = value;
        _spans[key] = span;
    }

    public bool TryGetValue(string key, out string? value)
        => _attributes.TryGetValue(key, out value);

    public bool TryGetSpan(string key, out TextSpan span)
        => _spans.TryGetValue(key, out span);

    public TextSpan? GetSpan(string key)
        => _spans.TryGetValue(key, out var span) ? span : null;

    public bool ContainsKey(string key)
        => _attributes.ContainsKey(key);

    public IEnumerable<KeyValuePair<string, string>> All()
        => _attributes;
}
