// <auto-generated>
// This code was generated by the Calor compiler.
// Do not modify this file directly.
// </auto-generated>

#nullable enable

using System;
using System.Collections.Generic;
using System.IO;

namespace AllowlistAudit
{
    public static class AllowlistAuditModule
    {
        private static bool StartsWith(string text, string prefix)
        {
            #line 11 "<source>.calr"
            int n = prefix.Length;
            #line default
            #line 12 "<source>.calr"
            if (n > text.Length)
            {
                #line 13 "<source>.calr"
                return false;
                #line default
            }

            #line default
            #line 14 "<source>.calr"
            return text.Substring(0, n) == prefix;
            #line default
        }

        private static bool EndsWith(string text, string suffix)
        {
            #line 18 "<source>.calr"
            int n = suffix.Length;
            #line default
            #line 19 "<source>.calr"
            int m = text.Length;
            #line default
            #line 20 "<source>.calr"
            if (n > m)
            {
                #line 21 "<source>.calr"
                return false;
                #line default
            }

            #line default
            #line 22 "<source>.calr"
            return text.Substring(m - n, n) == suffix;
            #line default
        }

        private static bool IsSkippable(string line)
        {
            #line 26 "<source>.calr"
            string t = line.Trim();
            #line default
            #line 27 "<source>.calr"
            if (t.Length == 0)
            {
                #line 28 "<source>.calr"
                return true;
                #line default
            }

            #line default
            #line 29 "<source>.calr"
            return StartsWith(t, "#");
            #line default
        }

        private static bool IsPendingMarker(string line)
        {
            #line 33 "<source>.calr"
            string t = line.Trim();
            #line default
            #line 34 "<source>.calr"
            return StartsWith(t, "# pending");
            #line default
        }

        private static bool IsStructurallyExempt(string path)
        {
            #line 38 "<source>.calr"
            if (StartsWith(path, "tests/"))
            {
                #line 39 "<source>.calr"
                return true;
                #line default
            }

            #line default
            #line 40 "<source>.calr"
            if (StartsWith(path, "bench/"))
            {
                #line 41 "<source>.calr"
                return true;
                #line default
            }

            #line default
            #line 42 "<source>.calr"
            if (StartsWith(path, "tools/Calor.RoundTrip.Harness/"))
            {
                #line 43 "<source>.calr"
                return true;
                #line default
            }

            #line default
            #line 44 "<source>.calr"
            return false;
            #line default
        }

        private static void Report(string entry, string problem)
        {
            #line 48 "<source>.calr"
            Console.WriteLine("  " + (entry + (" — " + problem)));
            #line default
        }

        public static int Main()
        {
            #line 52 "<source>.calr"
            string file = ".calor-csharp-allowlist";
            #line default
            #line 53 "<source>.calr"
            bool present = File.Exists(file);
            #line default
            #line 54 "<source>.calr"
            if (!present)
            {
                #line 55 "<source>.calr"
                Console.WriteLine("allowlist-audit: .calor-csharp-allowlist not found (run from the repository root).");
                #line default
                #line 56 "<source>.calr"
                return 2;
                #line default
            }

            #line default
            #line 58 "<source>.calr"
            string[] lines = File.ReadAllLines(file);
            #line default
            #line 59 "<source>.calr"
            List<string> seen = new List<string>();
            #line default
            #line 61 "<source>.calr"
            int findings = 0;
            #line default
            #line 62 "<source>.calr"
            int entries = 0;
            #line default
            #line 64 "<source>.calr"
            bool pending = false;
            #line default
            #line 65 "<source>.calr"
            Console.WriteLine("allowlist-audit: checking .calor-csharp-allowlist");
            #line default
            #line 66 "<source>.calr"
            foreach (var raw in lines)
            {
                #line 67 "<source>.calr"
                bool skip = IsSkippable(raw);
                #line default
                #line 68 "<source>.calr"
                if (skip)
                {
                    #line 75 "<source>.calr"
                    pending = IsPendingMarker(raw);
                    #line default
                }

                #line default
                #line 76 "<source>.calr"
                if (!skip)
                {
                    #line 77 "<source>.calr"
                    string entry = raw.Trim();
                    #line default
                    #line 78 "<source>.calr"
                    entries = entries + 1;
                    #line default
                    #line 80 "<source>.calr"
                    bool wild = entry.Contains("*");
                    #line default
                    #line 81 "<source>.calr"
                    if (wild)
                    {
                        #line 82 "<source>.calr"
                        Report(entry, "contains a wildcard; the allowlist requires specific paths");
                        #line default
                        #line 83 "<source>.calr"
                        findings = findings + 1;
                        #line default
                    }

                    #line default
                    #line 85 "<source>.calr"
                    bool isCs = EndsWith(entry, ".cs");
                    #line default
                    #line 86 "<source>.calr"
                    if (!isCs)
                    {
                        #line 87 "<source>.calr"
                        Report(entry, "is not a .cs path, so the guard can never match it");
                        #line default
                        #line 88 "<source>.calr"
                        findings = findings + 1;
                        #line default
                    }

                    #line default
                    #line 90 "<source>.calr"
                    if (seen.Contains(entry))
                    {
                        #line 91 "<source>.calr"
                        Report(entry, "is listed more than once");
                        #line default
                        #line 92 "<source>.calr"
                        findings = findings + 1;
                        #line default
                    }

                    #line default
                    #line 93 "<source>.calr"
                    seen.Add(entry);
                    #line default
                    #line 95 "<source>.calr"
                    bool exempt = IsStructurallyExempt(entry);
                    #line default
                    #line 96 "<source>.calr"
                    if (exempt)
                    {
                        #line 97 "<source>.calr"
                        Report(entry, "is under a structurally exempt tree, so the entry grants nothing and misleads");
                        #line default
                        #line 98 "<source>.calr"
                        findings = findings + 1;
                        #line default
                    }

                    #line default
                    #line 103 "<source>.calr"
                    if (!wild)
                    {
                        #line 104 "<source>.calr"
                        if (isCs)
                        {
                            #line 105 "<source>.calr"
                            bool onDisk = File.Exists(entry);
                            #line default
                            #line 110 "<source>.calr"
                            if (onDisk)
                            {
                                #line 111 "<source>.calr"
                                if (pending)
                                {
                                    #line 112 "<source>.calr"
                                    Report(entry, "is marked pending but now exists; remove the pending marker");
                                    #line default
                                    #line 113 "<source>.calr"
                                    findings = findings + 1;
                                    #line default
                                }

                                #line default
                            }

                            #line default
                            #line 114 "<source>.calr"
                            if (!onDisk)
                            {
                                #line 115 "<source>.calr"
                                if (pending)
                                {
                                    #line 116 "<source>.calr"
                                    Console.WriteLine("  " + (entry + " — pending: pre-registered, file not merged yet"));
                                    #line default
                                }

                                #line default
                                #line 117 "<source>.calr"
                                if (!pending)
                                {
                                    #line 118 "<source>.calr"
                                    Report(entry, "does not exist; a stale entry keeps permission alive for a path nothing occupies");
                                    #line default
                                    #line 119 "<source>.calr"
                                    findings = findings + 1;
                                    #line default
                                }

                                #line default
                            }

                            #line default
                        }

                        #line default
                    }

                    #line default
                    #line 122 "<source>.calr"
                    pending = false;
                    #line default
                }

                #line default
            }

            #line default
            #line 124 "<source>.calr"
            Console.WriteLine("allowlist-audit: " + entries + " entries, " + findings + " finding(s)");
            #line default
            #line 125 "<source>.calr"
            if (findings > 0)
            {
                #line 126 "<source>.calr"
                return 1;
                #line default
            }

            #line default
            #line 127 "<source>.calr"
            return 0;
            #line default
        }

    }
}
